### ISSUE TITLE
Allow Insecure Registries not working

### ISSUE THREAD

**Issue by SK360** [rancher/k3os#100]
We are trying to prototype k3os and have a need to pull from an insecure registry.  I tried adding 

`[plugins.cri.registry.mirrors]
[plugins.cri.registry.mirrors."your-insecure-registory:5000"]
endpoint = ["http://your-insecure-registory:5000"]`

to /var/lib/rancher/k3s/agent/etc/containerd/config.toml but it doesn't seem to work or persist.

**Comment by chtardif** [comment]
Created the /var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl from write_files module in /var/lib/rancher/k3os/config.yaml

The file config.toml.tmpl now gets created and persist over reboots (well..  actually it gets created every time, and I can see it used to complete the config.toml.

That said, it still doesn't work for insecure registries. :-(

**Comment by davidnuzik** [comment]
Reference https://github.com/rancher/k3s/issues/145 for this issue. We are tracking the issue there.
