### ISSUE TITLE
How can I set the timezone to other?

### ISSUE THREAD

**Issue by Jawenba** [rancher/k3os#103]
version: v0.2.1

#date
Mon May 20 08:11:46 UTC 2019

Can you  guide me to set time+8 for k3os，thanks!

**Comment by ivan98** [comment]
In my `config.yaml`, I have:
```
boot_cmd:
  - "echo SGT+8 > /etc/TZ"
```

**Comment by dweomer** [comment]
I'll add tzdata and some default symlinks soon.

**Comment by dweomer** [comment]
The tzdata info is now included in the rootfs via #428. I'll ad a readme entry that shows how to set your timezone.

**Comment by vdboor** [comment]
@dweomer would it be possible to have a `timezone` setting in the yaml file?

I'm glad I've found this ticket, having the dates in our own timezone makes scanning log files much easier.
