### ISSUE TITLE
How to install virtualbox guest additions in k3os ? 

### ISSUE THREAD

**Issue by lianghuiyuan** [rancher/k3os#107]
I run k3os in virtualbox6. but I can not use  sharefolder or keyboard or mouse ... as i want to share my server node-token with other nodes.
google told I should install guest additions, 
I tried install guest additions but failed. 
So, How could I install virtualbox guest additions in k3os ?

**Comment by szhilkin** [comment]
Installed latest VB, installed k3OS, keyboard and mouse work fine.
@lianghuiyuan Use ssh/scp. There is no need in VB guest tools.

**Comment by lianghuiyuan** [comment]
Ok，Thank you so much.
I think 'ssh/scp' works.
