### ISSUE TITLE
OpenEBS -  /run/udev is not a directory

### ISSUE THREAD

**Issue by vitobotta** [rancher/k3os#113]
I am trying to set up OpenEBS with k3OS but the node disk manager is not starting. The error is 

```
MountVolume.SetUp failed for volume "udev" : hostPath type check failed: /run/udev is not a directory
```

Any idea of what I can do to fix/work around it? Thanks

**Comment by bplein** [comment]
see also #151

**Comment by dweomer** [comment]
As per https://twitter.com/dweomer/status/1226289185054588933?s=20, I think OpenEBS on k3OS works now.
