### ISSUE TITLE
What is the difference between a `server` and an `agent`

### ISSUE THREAD

**Issue by jensenbox** [rancher/k3os#115]
There is nothing that I can see that describes what you are getting into if you select one vs the other.

What can an agent do or not do that a server can and visa-versa?

**Comment by axsc** [comment]
In a "big" cluster environment the master node organizes and controls the cluster. On the agent node you can deploy your pods.
Read more: https://kubernetes.io/docs/concepts/overview/components/

In smaller "one-node" environments the node acts as a server and an agent simultaneously.

**Comment by jensenbox** [comment]
Are you saying the "server" nodes run all "mast components" and "node components" while "agents" only run "node components"?

Does that mean for HA you have to run an odd number of masters greater than 1 as per the usual?

What reason other than the overhead would you simply just not run everything as a master? Seems reasonable to replicate the world everywhere - unless you have a gigantic world.

**Comment by axsc** [comment]
The server node can run all components, but it is not necessary in a cluster environment with dedicated agent nodes.
I cannot explain you why it is better to separate server and agent components. Maybe it is only a design decision.

Because of the split brain problem you should run at least 3 server nodes.

**Comment by pagong** [comment]
Please read the docs: k3OS and k3s are _currently_ unable to be used in HA mode.

**Comment by axsc** [comment]
Sorry, but where did you find this information?

**Comment by pagong** [comment]
> Sorry, but where did you find this information?

[Here](https://github.com/rancher/k3s#server-ha)

**Comment by mootari** [comment]
For those wondering where the those links pointed to originally: HA support was added in v0.7.0 and the readme [updated](https://github.com/rancher/k3s/commit/cef0fb7a74ca6e30280a7de08a2c5fe7b6ad4682#diff-04c6e90faac2675aa89e2176d2eec7d8) [accordingly](https://github.com/rancher/k3s/commit/2324406490d9d0e8d71fcd9a221e37d5c3e13e26#diff-04c6e90faac2675aa89e2176d2eec7d8).

**Comment by davidnuzik** [comment]
Closing. It appears the question has been addressed. Please note we have added some official documentation on the rancher.com docs site here for k3s: https://rancher.com/docs/k3s/latest/en/ I hope this is helpful as well.

We're continuing to improve k3s documentation and we anticipate later this year these docs will be expanded upon as well.
