### ISSUE TITLE
Make ami available for other regions

### ISSUE THREAD

**Issue by byrnedo** [rancher/k3os#117]
I would like to use the official k3os ami in 'eu-west-1' region for example.
I believe packer supports copying to multiple regions: https://www.packer.io/docs/builders/amazon-ebs.html#ami_regions

**Comment by dmc5179** [comment]
@byrnedo Do you know what region the official AMI is in now and what the AMI ID is?

**Comment by byrnedo** [comment]
@dmc5179 Its ami-04fb2ca5073400a8f in us-east-1 (N. Virginia)

**Comment by dmc5179** [comment]
@byrnedo I made that one yesterday using the packer tool since I couldn't find an official image anywhere. I'm in the process of testing to see if the image is working and making ansible playbooks to deploy a cluster on AWS

**Comment by byrnedo** [comment]
ahaa, ok, it's been a while but I'm pretty sure I found an ami in June when I made this issue.

**Comment by ls-brentsmith** [comment]
you can clone this repo, set  ` AWS_ACCESS_KEY_ID ` and ` AWS_SECRET_ACCESS_KEY ` and run ` packer build -var=region=us-west-2 template.json `  (or any other valid region) it will create an AMI for you in your AWS account.

**Comment by ls-brentsmith** [comment]
I ended up on this issue because I wanted the AWS packer template to allowed AWS_PROFILE instead of forcing the key/secret method. 

Is that something that would be a welcome addition here?

**Comment by byrnedo** [comment]
For my case that would work fine @ls-brentsmith

**Comment by dweomer** [comment]
@ls-brentsmith I would be happy to review such a change

**Comment by dweomer** [comment]
There is no official image for k3OS yet. The packer builds are provided to the community so that you may build your own.
