### ISSUE TITLE
[Question] Best way to set k3s arguments

### ISSUE THREAD

**Issue by furkanmustafa** [rancher/k3os#118]
I'd like to set `--flannel-iface=eth1` on k3s agent binary.

I have checked the openrc service file, and I've edited it manually, and it worked.

Now I'm looking for a better way than editing init file manually.

I have considered the following (on k3s repo);

```diff
diff --git a/install.sh b/install.sh
index 24e700487e..f1daf4fd31 100755
--- a/install.sh
+++ b/install.sh
@@ -514,17 +514,17 @@ start_pre() {
     rm -f /tmp/k3s.*
 }
 
+set -o allexport
+if [ -f /etc/environment ]; then source /etc/environment; fi
+if [ -f ${FILE_K3S_ENV} ]; then source ${FILE_K3S_ENV}; fi
+set +o allexport
+
 supervisor=supervise-daemon
 name="${SYSTEM_NAME}"
 command="${BIN_DIR}/k3s"
-command_args="${CMD_K3S_EXEC} >>${LOG_FILE} 2>&1"
+command_args="${CMD_K3S_EXEC} \${K3S_ARGS} >>${LOG_FILE} 2>&1"
 pidfile="/var/run/${SYSTEM_NAME}.pid"
 respawn_delay=5
-
-set -o allexport
-if [ -f /etc/environment ]; then source /etc/environment; fi
-if [ -f ${FILE_K3S_ENV} ]; then source ${FILE_K3S_ENV}; fi
-set +o allexport
 EOF
     $SUDO chmod 0755 ${FILE_K3S_SERVICE}
 
```

so I could edit one of the env files, and append arguments to k3s command.

Would that make sense, or would you do it in a different way?

I'd be glad to send a PR for this.

**Comment by liyimeng** [comment]
did you try k3sos.k3s_args?

**Comment by davidnuzik** [comment]
Closing. The comment provided should resolve the issue. Please do re-open if this didn't work for you.
