### ISSUE TITLE
upgrade / proxy / ip settings

### ISSUE THREAD

**Issue by schmitch** [rancher/k3os#122]
Hello I have some questions about k3os.

Mostly for IOT purposes will it be possible/is it already possible to change proxy and ip settings directly from k8s/k3s? that would actually help in configuring the system way better in a closed environment.

and also how can I actually update the system? and when will the so called k3os operator be ready?

**Comment by liyimeng** [comment]
I think k3os is designed by purpose that you are not able to change things after deployment, so called immutable OS.  If you wanna change settings like this, you need to do it in config file, like config.yaml, and restart.

**Comment by dweomer** [comment]
@schmitch upgrade isn't yet officially supported but the community has come up with some working examples. Please see https://github.com/rancher/k3os/issues/125#issuecomment-539857250

For IP/proxy settings please see https://github.com/rancher/k3os#networking. Note that up until the v0.3.0 release there was a bug preventing `k3os.environment` settings (where `http_proxy`/`https_proxy` should be set) from propagating to k3s. If you require more control over your network settings you will want to get familiar with connman and the `write_files` capability in `config.yaml`. If you have trouble getting this working please feel free to re-open.
