### ISSUE TITLE
Password for "rancher" expires and prevents login

### ISSUE THREAD

**Issue by ubergeek801** [rancher/k3os#123]
I have set up k3os on five Odroid N2 devices using the "overlay" method of installation. That process worked without a hitch.

However, upon subsequent login attempts, the following occurs:

```
WARNING: Your password has expired.
You must change your password now and login again!
passwd: must be suid to work properly
```

after which the ssh connection is dropped.

I suspect this happens because I have not connected a battery backup for the RTC, and thus whatever timestamps are used to determine password age are unreliable. While setting up the devices, I was able to reboot multiple times and log in as "rancher", but I noticed this issue started after power was disconnected.

Since many embedded devices don't have reliable RTCs, and it's meaningless to try to change the password anyway (as this is configured via config.yaml), it would be preferable if k3os initialized the system in such a way that the password never expires.

Thanks for considering this issue!

**Comment by ubergeek801** [comment]
In the meantime, I collected some backup batteries to verify that the RTC is indeed the cause. After powering up with RTC battery in place, then rebooting after a minute or so (to allow NTP to do its job), I am once again able to log in.

**Comment by davidnuzik** [comment]
Appears to have been resolved. Please re-open with details if this is not so :)
