### ISSUE TITLE
upgrade procedure question

### ISSUE THREAD

**Issue by YanChii** [rancher/k3os#125]
Hi,

If I understand correctly from README, the upgrade procedure is not yet implemented. But do we have at least something? I can't find anything anywhere, not even the code. 
And how will the upgrade work if I build my own k3os image?

Maybe I could help you with something here.

Thanks & Cheers.

Jan

**Comment by dweomer** [comment]
@YanChii until upgrades are officially supported, please see this from @zimme in the Rancher Users Slack: https://rancher-users.slack.com/archives/CJ75F6WJ3/p1570122380138300
> This is what I ran against my dev boards to update k3os in-place, incl k3s, `cd /k3os/system/; sudo mount -o remount rw .; sudo curl -LO https://github.com/rancher/k3os/releases/download/v0.3.0/k3os-rootfs-arm64.tar.gz; sudo tar xfz k3os-rootfs-arm64.tar.gz; sudo cp -R v0.3.0/k3os/system/* .; sudo rm -rf k3os-rootfs-arm64.tar.gz v0.3.0; sudo reboot`
