### ISSUE TITLE
0.6.x support

### ISSUE THREAD

**Issue by runningman84** [rancher/k3os#131]
It looks like there is no way to upgrade to 0.6.x yet.

**Comment by dweomer** [comment]
Hi @runningman84,

The latest k3OS release candidate supports k3s v0.8.1. If this doesn't meet your needs please re-open this issue or submit a new one.

Additionally, k3OS makes use of the k3s install.sh directly which you can pick the version for in [images/01-k3s/Dockerfile](../blob/v0.3.0-rc1/images/01-k3s/Dockerfile#L7) when building your own ISO.

If the option to build a custom ISO is not available, you may try overwriting `/usr/libexec/k3os/k3s-install.sh` (in a live install before running `os-config`) with the k3s install.sh of your choice, e.g.:
```bash
#!/bin/sh
K3S_VERSION=v0.9.0
K3S_INSTALL_URL="https://raw.githubusercontent.com/rancher/k3s/${K3S_VERSION}/install.sh"
K3S_INSTALL_PATH=/usr/libexec/k3os/k3s-install.sh
curl -fsSL "${K3S_INSTALL_URL}" | sudo tee "${K3S_INSTALL_PATH}" 1>/dev/null
# sudo os-config
```

**Comment by runningman84** [comment]
That's great to hear. What is the best way to upgrade a running cluster?
