### ISSUE TITLE
problem in doc regarding sysctls

### ISSUE THREAD

**Issue by kraney** [rancher/k3os#132]
In the README, the documentation defines the key *k3os.sysctls* - but the examples all use the key *sysctl* (without the 's'.) Which is it?

**Comment by dweomer** [comment]
@kraney param/config the processor uses some fuzzy matching for parameter names allowing for snake case and camel case for compound names and plural matching as well (see https://github.com/rancher/k3os#kernel-cmdline). If you run into an instance of the plural form not working as advertised please re-open this issue or submit a new one.
