### ISSUE TITLE
Support automated virt-install

### ISSUE THREAD

**Issue by jdmarble** [rancher/k3os#133]
I'm trying to automate an installation of k3os to a virtual machine using `virt-install` in an air-gapped environment. I've tried three different techniques so far:

### `--cdrom`

```
virt-install --connect=qemu:///session \
  --name k3os \
  --ram 2000 \
  --vcpus 2 \
  --disk path="k3os.qcow2",size=32 \
  --os-type linux \
  --os-variant ubuntu18.04 \
  --cdrom k3os-amd64.iso
```

This gets me to a point where I can perform an interactive installation. There's no way to pass kernel arguments using `--cdrom`, so I have to use a different argument to automate the installation.

### `--location`

With `--location`, I can specify kernel arguments and even inject `config.yaml`.

```
KERNEL_ARGS="\
 console=ttyS0,115200n8 \
 k3os.mode=install \
 k3os.install.silent=true \
 k3os.install.power_off=true \
 k3os.hostname=k3os \
"

virt-install --connect=qemu:///session \
  --name k3os \
  --ram 2000 \
  --vcpus 2 \
  --disk path="k3os.qcow2",size=32 \
  --console=pty,target_type=serial \
  --graphics none \
  --os-type linux \
  --os-variant ubuntu18.04 \
  --location k3os-amd64.iso \
  --initrd-inject config/config.yaml \
  --extra-args "${KERNEL_ARGS}"
```

Unfortunately, `virt-install` can not extract the kernel image from `k3os-amd64.iso`. Seems like the image doesn't provide joliet file info.

```Starting install...
isoinfo: Unable to find Joliet SVD
isoinfo: Unable to find Joliet SVD
isoinfo: Unable to find Joliet SVD
isoinfo: Unable to find Joliet SVD
isoinfo: Unable to find Joliet SVD
isoinfo: Unable to find Joliet SVD
isoinfo: Unable to find Joliet SVD
ERROR    Could not find an installable distribution at 'k3os-amd64.iso'
```

### `--boot`

I can specify the kernel and initrd using the `--boot` option.

```
KERNEL_ARGS="\
 console=ttyS0,115200n8 \
 k3os.mode=install \
 k3os.debug=true \
 k3os.install.silent=true \
 k3os.install.power_off=true \
 k3os.hostname=k3os \
"

virt-install --connect=qemu:///session \
  --name k3os \
  --ram 2000 \
  --disk path="k3os.qcow2",size=32 \
  --vcpus 2 \
  --graphics none\
  --boot kernel=k3os-vmlinuz-amd64,initrd=k3os-initrd-amd64,kernel_args="${KERNEL_ARGS}" \
  --cdrom k3os-amd64.iso \
  --console=pty,target_type=serial \
  --os-type linux \
  --os-variant ubuntu18.04
```

This boots, but fails at the installer.

```
Running k3OS configuration
Usage: /usr/libexec/k3os/install [--force-efi] [--debug] [--tty TTY] [--poweroff] [--takeover] [--no-format] [--config https://.../config.yaml] DEVICE ISO_URL

Example: /usr/libexec/k3os/install /dev/vda https://github.com/rancher/k3os/releases/download/v0.2.0/k3os.iso

DEVICE must be the disk that will be partitioned (/dev/vda). If you are using --no-format it should be the device of the K3OS_STATE partition (/dev/vda2)

The parameters names refer to the same names used in the cmdline, refer to README.md for
more info.

exit status 1
ERRO[0000] exit status 1 
```
(full log attached) [install.log](https://github.com/rancher/k3os/files/3316150/install.log)

At this point, I can't tell what is going wrong.

**Comment by dweomer** [comment]
@jdmarble @liamdawson

I wonder if adding `-J -joliet-long` to the [`xorriso` wrapper](https://github.com/rancher/k3os/blob/master/images/06-iso/wrapper#L4) would fix the ISO for your use case.

**Comment by liamdawson** [comment]
@dweomer I didn't try to automate virt-install using these techniques, my PR was looking to upstream another approach that achieved the same goal.

**Comment by insertjokehere** [comment]
FWIW, I managed to get the `--boot` option working like so:

```
virt-install \
  --import --disk /dev/guests/k3os-b,bus=virtio 
  --disk /var/lib/libvirt/images/k3os-amd64.iso,device=cdrom 
  --boot kernel=/var/lib/libvirt
/images/k3os-vmlinuz-amd64,initrd=/var/lib/libvirt/images/k3os-initrd-amd64,kernel_args="console=tty1 console=ttyS0 k3os.fallback_mode=install k3os.install.silent=true k3os.install.tty=ttyS0 k3os.install.device=/dev/vda k3os.install.config_url=http://guest-configs/config.yaml" \
  --network network=main \
  --console=pty,target_type=serial \
  --os-type linux \
  --os-variant generic \
  --graphics none
```

The important bit seems to be specifying the target disk, or the install command doesn't do anything

**Comment by Raqbit** [comment]
To boot & silent-install k3OS with `virt-install` I'm currently using the following setup:

```yaml
kernel_args="\
console=ttyS0 \
k3os.mode=install \
k3os.install.silent=true \
k3os.install.device=/dev/vda \
k3os.install.config_url=${config_url}
k3os.install.iso_url=${iso_url} \
k3os.hostname=${name} \
"

virt-install \
	--connect qemu:///session \
	--name $name \
	--disk size=8 \
	--ram 2048 \
	--vcpus 1 \
	--os-type linux \
	--os-variant ubuntu18.04 \
	--graphics none \
	--network bridge=virbr0 \
	--install kernel=${kernel_file},initrd=${initrd_file},kernel_args="${kernel_args}"
```

This works, but it needs to download the ISO file every time I setup a machine which is a bit annoying and I need a webserver to supply my k3OS config (Instead of using `--initrd-inject` with `--location`)

When trying to use `--location` and providing the ISO I run into the `isoinfo: Unable to find Joliet SVD` issue, although it only shows this with `--debug` for me (virt-install `v2.2.1`). 

This issue also happens when manually specifying the path of the kernel & initrd in the ISO image:
```
--location k3os-amd64.iso,kernel=/k3os/system/5.0.0-37-generic/kernel.squashfs,initrd=/k3os/system/5.0.0-37-generic/initrd
```

**Comment by dweomer** [comment]
@Raqbit re: --location flag/values

> ```
> --location k3os-amd64.iso,kernel=/k3os/system/5.0.0-37-generic/kernel.squashfs,initrd=/k3os/system/5.0.0-37-generic/initrd
> ```

@Raqbit these location values are missing the `/kernel/` infix path:
```
k3os-23449 [/mnt]$ df /mnt/
Filesystem     1K-blocks   Used Available Use% Mounted on
/dev/sr0          461686 461686         0 100% /mnt
k3os-23449 [/mnt]$ find /mnt/k3os/system/kernel | sort
/mnt/k3os/system/kernel
/mnt/k3os/system/kernel/5.0.0-37-generic
/mnt/k3os/system/kernel/5.0.0-37-generic/initrd
/mnt/k3os/system/kernel/5.0.0-37-generic/kernel.squashfs
/mnt/k3os/system/kernel/current
k3os-23449 [/mnt]$ 

```

**Comment by Raqbit** [comment]
> @Raqbit re: --location flag/values
> 
> > ```
> > --location k3os-amd64.iso,kernel=/k3os/system/5.0.0-37-generic/kernel.squashfs,initrd=/k3os/system/5.0.0-37-generic/initrd
> > ```
> 
> The location values you have supplied are missing the `/kernel/` infix path:
> 
> ```
> k3os-23449 [/mnt]$ df /mnt/
> Filesystem     1K-blocks   Used Available Use% Mounted on
> /dev/sr0          461686 461686         0 100% /mnt
> k3os-23449 [/mnt]$ find /mnt/k3os/system/kernel | sort
> /mnt/k3os/system/kernel
> /mnt/k3os/system/kernel/5.0.0-37-generic
> /mnt/k3os/system/kernel/5.0.0-37-generic/initrd
> /mnt/k3os/system/kernel/5.0.0-37-generic/kernel.squashfs
> /mnt/k3os/system/kernel/current
> k3os-23449 [/mnt]$ 
> ```

Oh sorry, that's a typo on my part.

```
virt-install \
	--connect qemu:///session \
	--name k3os \
	--disk size=8 \
	--ram 2048 \
	--vcpus 1 \
	--os-type linux \
	--os-variant ubuntu18.04 \
	--graphics none \
	--network bridge=virbr0 \
	--location k3os-amd64.iso,kernel=/k3os/system/kernel/5.0.0-37-generic/kernel.squashfs,initrd=/k3os/system/kernel/5.0.0-37-generic/initrd
```

is giving me:

```
Starting install...
ERROR    Command '['isoinfo', '-J', '-i', 'k3os-amd64.iso', '-f']' returned non-zero exit status 255.
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///session start k3os
otherwise, please restart your installation.
```

It seems like virt-install is running `isoinfo` despite me giving it instructions on where to find the kernel & initrd.

**Comment by dweomer** [comment]
> It seems like virt-install is running `isoinfo` despite me giving it instructions on where to find the kernel & initrd.
> 
> ```
> $ virt-install --version
> 2.2.1
> $ isoinfo --version
> isoinfo 1.1.11 (Linux)
> ```

Hmm, I thought I had fixed the ISO build to be more friendly with `isoinfo`

**Comment by Raqbit** [comment]
> > It seems like virt-install is running `isoinfo` despite me giving it instructions on where to find the kernel & initrd.
> > ```
> > $ virt-install --version
> > 2.2.1
> > $ isoinfo --version
> > isoinfo 1.1.11 (Linux)
> > ```
> 
> Hmm, I thought I had fixed the ISO build to be more friendly with `isoinfo`

Just to be clear, for me: 
```
$ isoinfo -J -i k3os-amd64.iso -f
isoinfo: Unable to find Joliet SVD
```

**Comment by Raqbit** [comment]
I'm still hitting the following issues when trying `virt-install`'s `--location` with the ISO generated by the current master (b279409fee99baecda5b71b5492c4254cd1c0bcf):

* Virt-install is not able to detect the kernel & initrd locations out of the box. If you look in the log of the second issue below, it does log about not finding a [treeinfo](https://release-engineering.github.io/productmd/treeinfo-1.0.html) file and some other files.
	```
	[wo, 04 mrt 2020 11:02:38 virt-install 14212] DEBUG (urldetect:42) Failed to acquire file=.treeinfo
	[wo, 04 mrt 2020 11:02:38 virt-install 14212] DEBUG (urldetect:42) Failed to acquire file=treeinfo
	[wo, 04 mrt 2020 11:02:38 virt-install 14212] DEBUG (urldetect:42) Failed to acquire file=content
	[wo, 04 mrt 2020 11:02:38 virt-install 14212] DEBUG (urldetect:42) Failed to acquire file=current/images/MANIFEST
	[wo, 04 mrt 2020 11:02:38 virt-install 14212] DEBUG (urldetect:42) Failed to acquire file=daily/MANIFEST
	[wo, 04 mrt 2020 11:02:38 virt-install 14212] DEBUG (urldetect:42) Failed to acquire file=.disk/info
	[wo, 04 mrt 2020 11:02:38 virt-install 14212] DEBUG (urldetect:42) Failed to acquire file=VERSION
	```

* Even when specifying the kernel & initrd locations, the vm creation will still fail. The following command:

	```
	virt-install \
		--connect qemu:///session \
		--name k3os \
		--disk size=8 \
		--ram 2048 \
		--vcpus 1 \
		--os-type linux \
		--os-variant ubuntu18.04 \
		--graphics none \
		--network bridge=virbr0 \
		--location ${iso_file},kernel=/k3os/system/kernel/5.0.0-41-generic/kernel.squashfs,initrd=/k3os/system/kernel/5.0.0-41-generic/initrd \
		--debug
	```

	results in the following log output log output: [gist](https://gist.github.com/Raqbit/c16f8e209336907e63af01d234930b73) (I replaced my home dir with `<home>`)

My host system is running the Ubuntu `5.3.0-40-generic` kernel at the moment.

**Comment by dweomer** [comment]
> I'm still hitting the following issues when trying `virt-install`'s `--location` with the ISO generated by the current master ([b279409](https://github.com/rancher/k3os/commit/b279409fee99baecda5b71b5492c4254cd1c0bcf)):
> 
> * Virt-install is not able to detect the kernel & initrd locations out of the box. If you look in the log of the second issue below, it does log about not finding a [treeinfo](https://release-engineering.github.io/productmd/treeinfo-1.0.html) file and some other files.
>   ```
>    [wo, 04 mrt 2020 11:02:38 virt-install 14212] DEBUG (urldetect:42) Failed to acquire file=.treeinfo
>    [wo, 04 mrt 2020 11:02:38 virt-install 14212] DEBUG (urldetect:42) Failed to acquire file=treeinfo
>    [wo, 04 mrt 2020 11:02:38 virt-install 14212] DEBUG (urldetect:42) Failed to acquire file=content
>    [wo, 04 mrt 2020 11:02:38 virt-install 14212] DEBUG (urldetect:42) Failed to acquire file=current/images/MANIFEST
>    [wo, 04 mrt 2020 11:02:38 virt-install 14212] DEBUG (urldetect:42) Failed to acquire file=daily/MANIFEST
>    [wo, 04 mrt 2020 11:02:38 virt-install 14212] DEBUG (urldetect:42) Failed to acquire file=.disk/info
>    [wo, 04 mrt 2020 11:02:38 virt-install 14212] DEBUG (urldetect:42) Failed to acquire file=VERSION
>   ```

This looks like noise to me as other log lines make it appear that libvirt has found the files in the ISO.

> * Even when specifying the kernel & initrd locations, the vm creation will still fail. The following command:
>   ```
>    virt-install \
>    	--connect qemu:///session \
>    	--name k3os \
>    	--disk size=8 \
>    	--ram 2048 \
>    	--vcpus 1 \
>    	--os-type linux \
>    	--os-variant ubuntu18.04 \
>    	--graphics none \
>    	--network bridge=virbr0 \
>    	--location ${iso_file},kernel=/k3os/system/kernel/5.0.0-41-generic/kernel.squashfs,initrd=/k3os/system/kernel/5.0.0-41-generic/initrd \
>    	--debug
>   ```
>   
>   
>   results in the following log output log output: [gist](https://gist.github.com/Raqbit/c16f8e209336907e63af01d234930b73) (I replaced my home dir with `<home>`)
> 
> My host system is running the Ubuntu `5.3.0-40-generic` kernel at the moment.

I see this error: `qemu: linux kernel too old to load a ram disk` in the log you linked.
**_I also see this when I modify my local qemu script to use the squashfs file as the kernel._**
I don't know how to do this in libvirt but if you can't emulate what is in GRUB, i.e. https://github.com/rancher/k3os/blob/master/install.sh#L161-L165, then you will need to open up the ISO and pluck the initrd+kernel.squashfs from it and then mount the kernel.squashfs on loopback before running your `virt-install` command.

**Comment by dweomer** [comment]
Alternatively, you could always just download the kernel and initrd from the releases page (right next to the ISO).

**Comment by alanlaird** [comment]
Following along this pattern, I'm able to virt-install a kvm guest using --boot arguments of the kernel and initrd and then k3os arguments to specify config.yaml and iso.  I feel like i'm missing something as it seems to install with no errors, reboot and want to install again.  
A good example of how we could install k3os with virt-install would be really useful.

**Comment by dweomer** [comment]
> Following along this pattern, I'm able to virt-install a kvm guest using --boot arguments of the kernel and initrd and then k3os arguments to specify config.yaml and iso. I feel like i'm missing something as it seems to install with no errors, reboot and want to install again.
> A good example of how we could install k3os with virt-install would be really useful.

The reboot is likely because of the `k3os.mode=install` kernel parameter lacking a corresponding `k3os.install.power_off=true` (due to a change some months back). It's not great, but that should get you install finished.

Make sure you put these kernel parameters in the `--extra-args` flag passed to `virt-install` so that your domain/vm does not continue to install-then-poweroff/reboot on start.

**Comment by larssb** [comment]
Here I am, finding myself writing on a closed issue. But, once again the issue perfectly fits my challenge.

**WHAT I'M DOING**

I'm trying to install K3OS via `virt-install` on an Ubuntu server v20.04 (LTS). I've installed the required prerequisites and the `KVM` install went through without issues.
I've downloaded the K3OS iso release [v0.10.1](https://github.com/rancher/k3os/releases/tag/v0.10.1) matching my platform *(x86_64)*. The cmdlines I've tried are:

1. `virt-install --name k3osvm1 --disk size=4 --ram 1024 --vcpus 1  --os-type linux --os-variant ubuntu20.04 --graphics none --network bridge=virbr0  --location ./installs/k3os-amd64.iso,kernel=/k3os/system/kernel/5.0.0-43-generic/kernel.squashfs,initrd=/k3os/system/kernel/5.0.0-43-generic/initrd --debug`
1. `virt-install --name k3osvm1 --disk size=4 --ram 1024 --vcpus 1  --os-type linux --os-variant ubuntu20.04 --graphics none --network bridge=virbr0  --location ./installs/k3os-amd64.iso,kernel=/k3os/system/kernel/5.0.0-43-generic/kernel.squashfs,initrd=/k3os/system/kernel/5.0.0-43-generic/initrd --boot kernel=./installs/k3os-kernel-amd64.squashfs,initrd=./installs/k3os-initrd-amd64 --debug`

The error I get is:

```
[Tue, 19 May 2020 14:56:50 virt-install 39561] DEBUG (cli:263)   File "/usr/share/virt-manager/virt-install", line 1005, in <module>
    sys.exit(main())
  File "/usr/share/virt-manager/virt-install", line 999, in main
    start_install(guest, installer, options)
  File "/usr/share/virt-manager/virt-install", line 686, in start_install
    fail(e, do_exit=False)
  File "/usr/share/virt-manager/virtinst/cli.py", line 263, in fail
    log.debug("".join(traceback.format_stack()))

[Tue, 19 May 2020 14:56:50 virt-install 39561] ERROR (cli:264) internal error: qemu unexpectedly closed the monitor: 2020-05-19T14:56:50.318303Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48FH).vmx-exit-load-perf-global-ctrl [bit 12]
2020-05-19T14:56:50.318374Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(490H).vmx-entry-load-perf-global-ctrl [bit 13]
qemu: linux kernel too old to load a ram disk
[Tue, 19 May 2020 14:56:50 virt-install 39561] DEBUG (cli:266) 
Traceback (most recent call last):
  File "/usr/share/virt-manager/virt-install", line 657, in start_install
    domain = installer.start_install(guest, meter=meter,
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 542, in start_install
    domain = self._create_guest(
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 491, in _create_guest
    domain = self.conn.createXML(install_xml or final_xml, 0)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 4034, in createXML
    if ret is None:raise libvirtError('virDomainCreateXML() failed', conn=self)
libvirt.libvirtError: internal error: qemu unexpectedly closed the monitor: 2020-05-19T14:56:50.318303Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(48FH).vmx-exit-load-perf-global-ctrl [bit 12]
2020-05-19T14:56:50.318374Z qemu-system-x86_64: warning: host doesn't support requested feature: MSR(490H).vmx-entry-load-perf-global-ctrl [bit 13]
qemu: linux kernel too old to load a ram disk
[Tue, 19 May 2020 14:56:50 virt-install 39561] DEBUG (installer:565) Removing created disk path=/var/lib/libvirt/images/k3osvm1.qcow2 vol_object=<libvirt.virStorageVol object at 0x7fecfef9a4f0>
Removing disk 'k3osvm1.qcow2'                                                                                                                          |    0 B  00:00:00     
[Tue, 19 May 2020 14:56:50 virt-install 39561] DEBUG (cli:278) Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start k3osvm1
otherwise, please restart your installation.
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start k3osvm1
otherwise, please restart your installation.
```

**TRYING**

- To avoid loading from external URI's
- Doing a headless/non-interactive installation of K3OS

**DISCLAIMER**

I'm no `KVM` expert. But I do have searched far and wide for how-to's on this.

---

I hope that someone here can help. Maybe you/very likely you @dweomer ....

Thank you so much 💯

**Comment by dweomer** [comment]
Booting from the ISO won’t work with virt-install because the embedded boot loader doesn’t know what to do with the squashfs file. Download the kernel and initrd from the releases page and use those directly (have the iso mounted for install. Additionally, consider a 2GB minimum for memory if you want any overhead for OS and pods.

**Comment by larssb** [comment]
So @dweomer,

Does that mean I should use the `-location` method? Like so:

`virt-install ... --location ~/k3os-amd64.iso`. But what are the parameters I need to specify to point to the `kernel` and `initrd` file.

Or will `virt-install` simply somehow catch that the K3OS iso is mounted?

2GB sure. I'll gladly give it that amount of RAM. Thank you.

**Comment by dweomer** [comment]
@larssb you can reference the `start.sh` at https://github.com/rancher/k3os/issues/395#issue-578502683

**Comment by larssb** [comment]
Thank you very much ... that got me going. Really appreciate it Mr. @dweomer 🥇 now I just have to configure out how-to properly setup K3OS. I'll get there.

Thanks
