### ISSUE TITLE
/etc/rc.local is not run

### ISSUE THREAD

**Issue by liyimeng** [rancher/k3os#135]
When using right file to run commands into /etc/rc.local, the command was not executed during system boot.

**Comment by ubergeek801** [comment]
k3os doesn't use a traditional init, but instead allows init_cmd, boot_cmd and run_cmd to be specified in config.yaml (see [this section](https://github.com/rancher/k3os#init_cmd-boot_cmd-run_cmd) of the readme).

**Comment by dweomer** [comment]
Yes, as per @ubergeek801 comment above, `rc.local` is not invoked but you do have the option of using `init_cmd`, `boot_cmd`, and `run_cmd`. Additionally, anything dropped into `/etc/local.d` via `write_files` should get invoked with the "local" catch-all service that runs after everything else in the `default` run-level.
