### ISSUE TITLE
not work release k3s 0.7.0

### ISSUE THREAD

**Issue by andruwa13** [rancher/k3os#150]
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by andruwa13** [comment]
fixed:
run command `/usr/local/bin/k3s-uninstall.sh`

**Comment by runningman84** [comment]
How do you even run a recent k3s release on k3os? It looks like k3os was not updated for months...

**Comment by andruwa13** [comment]
@runningman84 
run command:
curl -sfL https://get.k3s.io | sh -
/usr/local/bin/k3s-killall.sh
sudo k3s server

**Comment by runningman84** [comment]
Hmm I thought k3os would use some operator to update k3s and the system would be somehow write protected.

**Comment by runningman84** [comment]
@ibuildthecloud do you have any eta for a new k3os release?

**Comment by dweomer** [comment]
Please see https://github.com/rancher/k3os/issues/173#issuecomment-531636552 and note that this was fixed in #181
