### ISSUE TITLE
Remastering ISO Documentation

### ISSUE THREAD

**Issue by joharper54SEG** [rancher/k3os#160]
I am remastering the ISO to add kernel parameters to grub.cfg.  I found a couple of differences between the process I had to take vs the documented process.  This was done on Ubuntu 16.04.

Problem: grub-mkrescue: warning: Your xorriso doesn't support `--grub2-boot-info'
Solution: sudo apt-get install xorriso

Problem:  (grub-mkrescue -o k3os-new.iso iso/ -V K3OS), the -V option only outputs the version info, it does not set the volume ID or create the ISO.  This will display a warning when booting from the ISO.
Solution: grub-mkrescue -o k3os-new.iso iso/ -- -volid K3OS

**Comment by dweomer** [comment]
Fixed by #165
