### ISSUE TITLE
kubectl can not connect to apiserver

### ISSUE THREAD

**Issue by majkrzak** [rancher/k3os#164]
After fresh installation kubectl is trying to connect to the localhost:8080, no `/etc/rancher/` something file with cluster admin credentials. It happen today around 12, I thought it is my fault, but it seems that something is messed up.

**Comment by dweomer** [comment]
Hi @majkrzak, can you tell us what version of k3os you are running (`master` or a download from [the releases page](/rancher/k3os/releases) or ...) and local/cloud, baremetal/vm?

**Comment by majkrzak** [comment]
I'm terribly sorry, I've forgot to remove the ticket yesterday. The issue
was that dns go to wild and everything under the cluster domain (host field
in config) was resolved into the cluster main ip, thanks to *.mydomsin.com
dns record. And version is 0.2.0. I've also noticed that you hadn't done
any upgrade last time.
