### ISSUE TITLE
Unable to read k3s.yaml

### ISSUE THREAD

**Issue by joharper54SEG** [rancher/k3os#173]
Imaging new host via refactored ISO from rc2.  Getting error running kubectl logged in as the rancher user.  Run the same command with sudo and it will succeed.  This is new behaviour in rc2, not sure if it's intentional or not.

s10618svr [~]$ kubectl get node
WARN[2019-09-13T13:59:26.157674721Z] Unable to read /etc/rancher/k3s/k3s.yaml, please start server with --write-kubeconfig-mode to modify kube config permissions
error: Error loading config file "/etc/rancher/k3s/k3s.yaml": open /etc/rancher/k3s/k3s.yaml: permission denied

s10618svr [~]$ ls -l /etc/rancher/k3s/k3s.yaml
-rw------- 1 root root 1052 Sep 13 13:56 /etc/rancher/k3s/k3s.yaml

s10618svr [~]$ sudo kubectl get node
NAME         STATUS     ROLES    AGE     VERSION
k3os-18447   NotReady   master   6m24s   v1.14.6-k3s.1
s10618svr    Ready      master   5m17s   v1.14.6-k3s.1

**Comment by ibuildthecloud** [comment]
@dweomer In k3s we changed the k3s.yaml to not be world readable by default.  In k3os I think should allow the rancher user to read the k3s.yaml by default.

**Comment by dweomer** [comment]
fixed by #181
