### ISSUE TITLE
Failed to connect to socket /run/dbus/system_bus_socket

### ISSUE THREAD

**Issue by debianmaster** [rancher/k3os#183]
My service interacts with a hardware device on the host and hence requires privileged access.
I have given privileged permission to pod, i can see t /run/dbus/system_bus_socket . file on the host but seeing this  error in pod logs

```
Inserting the driver ax99100-4.15.0-62-generic.ko into kernel...
insmod: ERROR: could not load module /opt/pyfarm/asix-driver/ax99100-4.15.0-62-generic.ko: No such file or directory
Setting the network speed of BR...
Error 2
Can't open /dev/ttyF0
Copying wpantund configuration...
Restarting DBUS to use updated wpantund config...
Failed to get D-Bus connection: Operation not permitted
Restarting systemd-logind to prevent slow login...
Failed to get D-Bus connection: Operation not permitted
Creating bq0 network interface...
./driver-init.sh: line 26: ip: command not found
./driver-init.sh: line 27: ip: command not found
./driver-init.sh: line 28: ip: command not found
Starting wpantund in background...
wpantund[17]: Starting wpantund 0.08.00d (Sep 12 2019 07:31:08) . . .
wpantund[17]: 	BUILD_VERSION = f84579f
wpantund[17]: Configuration file "/etc/wpantund.conf" read.
wpanctl.c:571: Requirement Failed (Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory)
Setting network parameters...
wpanctl.c:571: Requirement Failed (Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory)
wpantund[17]: DBUSIPCServer.cpp:70: Requirement Failed (Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory)
wpantund[17]: Unable to start DBUSIPCServer "std::exception"
wpantund[17]: Running as root without dropping privileges!
```

**Comment by dweomer** [comment]
@debianmaster if you are capable of compiling and running a custom ISO I would be interested in the results of downgrading the alpine base image to 3.9 from 3.10. change [images/00-base/Dockerfile](https://github.com/rancher/k3os/blob/master/images/00-base/Dockerfile#L2) and invoke `make build package` on linux or mac (with recent-ish Docker and make installed).

**Comment by dweomer** [comment]
@debianmaster: both @ibuildthecloud and I have run into spurious unavailability of dbus which is also effecting connman. I am working on a reversion to alpine 3.9 for the base, see #184, that should address this along with some networking tweaks.

**Comment by debianmaster** [comment]
thanks @dweomer ,  temporarily i switched to a different OS, i'll check back on this in few days.
