### ISSUE TITLE
Install k3OS: Allow to download cloud-config file self-sign certificates 

### ISSUE THREAD

**Issue by linuxmail** [rancher/k3os#185]
Hello,

I'm using the ISO file for AMD64 and it seems, its not possible to get the cloud-config file via HTTPS, if the cert is not recognized.  Either I have to download the file with "curl -k", or use HTTP, instead of HTTPS.
It would be great, if there is an option to allow that. 

cu denny

**Comment by dweomer** [comment]
Hi @linuxmail,

Unless you want to build a custom ISO with your self-signed cert then `curl -k` is your best option.
