### ISSUE TITLE
Are k3os support etcd or consul?

### ISSUE THREAD

**Issue by patsevanton** [rancher/k3os#186]
I mean k3os run single node or join to exist Kubernetes cluster

Are k3os support etcd or consul when run single node?

**Comment by dweomer** [comment]
@patsevanton I believe that there is currently experimental support for HA in k3s but I do not know if we will be supporting both etcd and consul. You may find the discussion at https://github.com/rancher/k3s/issues/42 (and related issues) to be helpful.

**Comment by davidnuzik** [comment]
Closing as Jacob mentioned refer to https://github.com/rancher/k3s/issues/42
