### ISSUE TITLE
Updating Traefik version

### ISSUE THREAD

**Issue by timothysparg** [rancher/k3os#198]
I'm trying to update Traefik version, but my attempts so far have failed. 

- I've tried updating the helm chart that lives at `/var/lib/rancher/k3s/server/manifests/traefik.yaml:`, but this seems to be overridden on restart
- I've tried using the `write_files` option in the `config.yaml` but this seems to be ignored

Is there another method that I should try?

**Comment by dweomer** [comment]
@timothysparg please take a look at https://github.com/rancher/k3os#k3osk3s_args. I think you need to pass something like `[server, --no-deploy=traefik]` to the `k3os.k3s_args` and then make sure your custom manifest is in `/var/lib/rancher/k3s/server/manifests/traefik.yaml`

**Comment by timothysparg** [comment]
@dweomer thanks! That seemed to do the trick. Is this something that would be handled by the K3os operator in the future, or is this the accepted method ?

**Comment by dweomer** [comment]
@timothysparg I do expect that the upgrade operator will incidentally upgrade Traefik that is bundled with k3s when when upgrading k3s if k3s itself relies on an upgraded version of Traefik. However, there will always be those that want/need to be running the latest and greatest Traefik (or other potentially future, bundled service) and hence this simple "no thanks, I can install it myself" override mechanism.
