### ISSUE TITLE
does not takeover rancheros

### ISSUE THREAD

**Issue by rbucker** [rancher/k3os#200]
if you're not going to support installation from docker-machine onto vsphere then it would be great if the install.sh script could takeover a rancheros installation. At least there would be a path to k3os on vmware

**Comment by dweomer** [comment]
As mentioned in #201, please see https://github.com/rancher/k3s/issues/73

**Comment by rbucker** [comment]
So the answer is... k3s uses containerd and rancher is docker. they work together but add layers of junk to get there. I'll have to take that at face value but it's all the more reason for k3os to support docker-machine.

Orchestration through simple tools is my motto.
