### ISSUE TITLE
The network is offline - net-online failed to start

### ISSUE THREAD

**Issue by joharper54SEG** [rancher/k3os#203]
Attempting to image a device using the refactored ISO method and k3os v0.3.0.  During boot, it stops at "checking to see if the network is online".  After a 5 minutes wait it errors out and the imaging process does not complete.  The machine is on the network and is pulling an IP via DHCP. 

![image](https://user-images.githubusercontent.com/46793278/66337808-dc37c580-e90d-11e9-8bee-0b7fbdc38ff8.png)

Looking in /var/log/messages I see where it looks like its attempting to access "http://ipv4.connman.net/online/status.html" and failing.  This system will not have internet access so need a way to do an offline install or change this check to an internal URL.

daemon.err connmand[1421]: Failed to find URL:http://ipv4.connman.net/online/status.html
connmand[1421]: IPv4 online check failed for 0x558e3c31b1a0 Wired

**Comment by dweomer** [comment]
@joharper54SEG please review https://github.com/rancher/k3os/blob/ef63b361488a4fe63895bb603a1d295c150edcaf/overlay/etc/conf.d/net-online#L13

It may be that you do not need the ping test (not using github ssh keys?). If your NIC has an IP from DHCP then the timeout is likely because the ping test is failing to lookup google.com (the default target). Consider changing the ping test target but also verify that the DNS configuration that you re are getting from DHCP is functional. If you're behind a proxy consider turning off the ping test or pointing at reachable host.

**Comment by joharper54SEG** [comment]
@dweomer  Thanks I will give that a shot.  I also updated the original post with additional details you may not have seen.

**Comment by dweomer** [comment]
@joharper54SEG connman phoning home shouldn't be the cause of the delay as the ping test fails for me in a reasonable time frame (with a custom net-online timeout value of 10-15 seconds) in an isolated network via qemu. My hunch is that pointing the ping test to a reachable host or just disabling it altogether will work for you.

**Comment by joharper54SEG** [comment]
@dweomer Stupid question time.  How would I go about modifying the net-online file?  I don't see the files written to the ISO anywhere so I am guessing I need to recompile and create a new ISO?  Compiling is outside of my normal wheelhouse so not quite sure what I'm doing there, but I would love to learn.

**Comment by dweomer** [comment]
@joharper54SEG I interpreted "Attempting to image a device using the refactored ISO method" from your original comment as building your own ISO. If that's not what you are doing then you would likely be best served by a k3OS `config.yaml` at `os-config` time, e.g.:
```yaml
write_files:
- encoding: ""
  content: |-
    minimum_up=1
    include_ping_test=no
    timeout=15
  owner: root
  path: /etc/conf.d/net-online
  permissions: '0644'
```

But this will still hang and eventually timeout when booting the ISO as you've described, which is time-consming. To avoid this you can make the equivalent modification I've listed above to [overlay/etc/conf.d/net-online](https://github.com/rancher/k3os/blob/ef63b361488a4fe63895bb603a1d295c150edcaf/overlay/etc/conf.d/net-online) and compile your custom ISO (provided you have `make`, `curl`, and `docker` installed on Linux or macOS) by invoking `make` at the checkout root.

**Comment by joharper54SEG** [comment]
@dweomer recompiling from source after modifying net-online as you described has resolved the issue.  Are there any plans to add a way to update this parameter without a recompile?

**Comment by dweomer** [comment]
@joharper54SEG right now a custom ISO is the best solution for installation in isolated networks.
