### ISSUE TITLE
/opt mentioned by README.md but it does not exist

### ISSUE THREAD

**Issue by frafra** [rancher/k3os#207]
I suggest to remove `/opt` from `README.md` as it is not available.

**Comment by dweomer** [comment]
Unless you are booting from ISO you can create the `/opt` directory and it will persist through reboots.

**Comment by frafra** [comment]
If `/` is persistent in general, it would be better to specify that in `README.md`.

Do you suggest to keep referencing to `/opt` even if it is not there? Or is it expected to be there?

**Comment by dweomer** [comment]
We reserve the right to do funky things with `/` so I will have to fix it so that `/opt` exists as expected.
