### ISSUE TITLE
Checking to see if the network is online

### ISSUE THREAD

**Issue by epnixsite** [rancher/k3os#211]
This is broken.. It doesn't work behind proxy. Need option to disable this, else timing out for ages ~ around 7 minutes during each boot.

**Comment by dweomer** [comment]
@epnixsite please take a look at a recent issue that overcame the same problem:
- https://github.com/rancher/k3os/issues/203#issuecomment-539147240
- https://github.com/rancher/k3os/issues/203#issuecomment-539170875

If rebuilding the ISO isn't an option for you then this wont do you much good when booting from the ISO but the advice above will completely sidestep the long waits when booting installed v0.3.0 systems.

All that said, I will readily admit that we do need a better experience for fresh air-gapped / firewalled installs.

**Comment by epnixsite** [comment]
I understand this and inspected scripts on githhub.. But these checks doesn't make any sense..
If you spinning k3os behind proxy - at least it should use /etc/environments to use HTT{P,PS}_PROXY vars and etc.. In previous versions it was working fine, why this has been added? Also ping in most corp environments would be disabled - so is invalid test too..

**Comment by dweomer** [comment]
Fixed via #249
