### ISSUE TITLE
k3os / k3s_args: some args in cloud config file no longer works - parsing is broken

### ISSUE THREAD

**Issue by epnixsite** [rancher/k3os#212]
For example: this no longer accepts:

 - "--no-deploy traefik"

Before was accepting extra args, now nope..

k3os:
  k3s_args:
  - server
  - "--no-deploy traefik"

-> with following setup k3s will not start - it will complain about incorrect flag/argument

**Comment by epnixsite** [comment]
For more info:
`k3s-master1 [~]$ ps axu | grep k3s
root      2620  0.0  0.0    896   548 ?        S    14:54   0:00 supervise-daemon k3s-service --start --stdout /var/log/k3s-service.log --stderr /var/log/k3s-service.log --pidfile /var/run/k3s-service.pid --respawn-delay 5 /sbin/k3s -- server -no-deploy traefik --kubelet-arg register-with-taints=key1=value1:NoSchedule --kubelet-arg register-with-taints=key1=value1:NoExecute
rancher   2937  0.0  0.0   1528     4 pts/0    S+   14:58   0:00 grep k3s
k3s-master1 [~]$ tail -f /var/log/k3s-service.log
   --flannel-iface value               (agent) Override default flannel interface
   --container-runtime-endpoint value  (agent) Disable embedded containerd and use alternative CRI implementation
   --pause-image value                 (agent) Customized pause image for containerd sandbox
   --resolv-conf value                 (agent) Kubelet resolv.conf file [$K3S_RESOLV_CONF]
   --kubelet-arg value                 (agent) Customized flag for kubelet process
   --kube-proxy-arg value              (agent) Customized flag for kube-proxy process
   --node-label value                  (agent) Registering kubelet with set of labels
   --node-taint value                  (agent) Registering kubelet with set of taints

time="2019-10-10T14:58:25Z" level=fatal msg="flag provided but not defined: -no-deploy traefik"`

**Comment by DarkBlaez** [comment]
Yes the cloud-init parsing in k3os install is a basic shit-show. Does not even take in to consideration when the format changes and the docs are outdated

-DB

**Comment by vtolj** [comment]
I know this is a little bit outdated but this worked for me:
`'no-deploy=traefik' \`

**Comment by kzorluoglu** [comment]
now it is `--disable=traefik`

For Installation:
`curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable=traefik" sh -s -
`
For Config:
`'--disable=traefik' \`
