### ISSUE TITLE
Release v0.5.0 failing to boot. 

### ISSUE THREAD

**Issue by amackillop** [rancher/k3os#245]
I am trying to create a virtual machine using KVM on Manjaro with the latest release of k3os found [here](https://github.com/rancher/k3os/releases/download/v0.5.0/k3os-amd64.iso).

Unfortunately it fails to boot. I gave it 2 gigs of ram and 2 cpus. This is how it fails:

![k3os](https://user-images.githubusercontent.com/33668612/67627426-41eee180-f82a-11e9-8831-dadde87e6c06.png)

If I use the run script it boots and works as expected.

**Comment by dweomer** [comment]
@amackillop does this happen for you with [v0.4.0](https://github.com/rancher/k3os/releases/tag/v0.4.0)?

**Comment by amackillop** [comment]
@dweomer 
Version 4.0 does boot successfully.

**Comment by dweomer** [comment]
> @dweomer
> Version 0.4.0 does boot successfully. However, I was not able to login after installing to disk. I tried using `rancher` as the password. SSH as rancher does work though.

If you don't supply a password via `config.yaml` when installing (`os-config` asks you for one and generates this for you) then yes, password login will not work which leaves ssh authorized keys.

---

I don't run Manjaro but the v0.5.0 ISO boots for me in:
- VirtualBox 5.2.32 on Ubuntu 18.04.3
- Qemu 2.11.1 on Ubuntu 18.04.3
- Qemu 4.1 on macOS Mojave

Can you share the qemu command your system is using to launch? e.g.
```
qemu-system-x86_64 -cdrom k3os-amd64.iso -m 2048 -smp 2 -machine accel=kvm
```

**Comment by cro** [comment]
Sorry, I have the same problem creating a VM under Proxmox 6, kvm with q35 and the default i440fx machine types.  My screen looks almost exactly like the screenshot above.

**Comment by dweomer** [comment]
@cro I've not used Proxmox but it looks like a bundled Debian (with Qemu). Can you drop to a terminal and capture the `/proc/<pid>/cmdline` of the process running the VM? Something like:
```
# where 12345 is the pid of the `qemu-system-x86_64` process
sudo strings < /proc/12345/cmdline
```

Without knowing more about how your VMs are being launched it is difficult to diagnose the problem that you are having.

**Comment by amackillop** [comment]
@dweomer 

Here is the command being run:

```
/usr/bin/qemu-system-x86_64 -name guest=k3s,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-6-k3s/master-key.aes -machine pc-i440fx-4.1,accel=kvm,usb=off,vmport=off,dump-guest-core=off -cpu Skylake-Client-IBRS,ss=on,hypervisor=on,tsc-adjust=on,clflushopt=on,umip=on,md-clear=on,stibp=on,ssbd=on,xsaves=on,pdpe1gb=on,skip-l1dfl-vmentry=on,hle=off,rtm=off -m 2048 -overcommit mem-lock=off -smp 2,sockets=2,cores=1,threads=1 -uuid 1f96854b-eec4-46a3-9c35-b2cfb57f3d73 -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=35,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=delay -no-hpet -no-reboot -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -boot strict=on -device ich9-usb-ehci1,id=usb,bus=pci.0,addr=0x5.0x7 -device ich9-usb-uhci1,masterbus=usb.0,firstport=0,bus=pci.0,multifunction=on,addr=0x5 -device ich9-usb-uhci2,masterbus=usb.0,firstport=2,bus=pci.0,addr=0x5.0x1 -device ich9-usb-uhci3,masterbus=usb.0,firstport=4,bus=pci.0,addr=0x5.0x2 -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x6 -drive file=/var/lib/libvirt/images/k3s.qcow2,format=qcow2,if=none,id=drive-ide0-0-0 -device ide-hd,bus=ide.0,unit=0,drive=drive-ide0-0-0,id=ide0-0-0,bootindex=2 -drive file=/var/lib/libvirt/images/k3os-amd64.iso,format=raw,if=none,id=drive-ide0-0-1,readonly=on -device ide-cd,bus=ide.0,unit=1,drive=drive-ide0-0-1,id=ide0-0-1,bootindex=1 -netdev tap,fd=37,id=hostnet0 -device e1000,netdev=hostnet0,id=net0,mac=52:54:00:88:88:43,bus=pci.0,addr=0x3 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -chardev spicevmc,id=charchannel0,name=vdagent -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=com.redhat.spice.0 -device usb-tablet,id=input0,bus=usb.0,port=1 -spice port=5901,addr=127.0.0.1,disable-ticketing,image-compression=off,seamless-migration=on -device qxl-vga,id=video0,ram_size=67108864,vram_size=67108864,vram64_size_mb=0,vgamem_mb=16,max_outputs=1,bus=pci.0,addr=0x2 -device intel-hda,id=sound0,bus=pci.0,addr=0x4 -device hda-duplex,id=sound0-codec0,bus=sound0.0,cad=0 -chardev spicevmc,id=charredir0,name=usbredir -device usb-redir,chardev=charredir0,id=redir0,bus=usb.0,port=2 -chardev spicevmc,id=charredir1,name=usbredir -device usb-redir,chardev=charredir1,id=redir1,bus=usb.0,port=3 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x7 -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on
```

**Comment by cro** [comment]
v0.6.0-rc1 exhibits the same behavior.  I am getting a shell account on the host to retrieve the process cmdline.  Will post here.

**Comment by cro** [comment]
Nevermind, I figured it out.  It won't boot on Proxmox if the video card is set to SPICE.  Switching that to `Default` took care of it.

**Comment by dweomer** [comment]
> Nevermind, I figured it out. It won't boot on Proxmox if the video card is set to SPICE. Switching that to `Default` took care of it.

@amackillop from the cmdline that you've share it looks like spice might be the culprit for you as well

**Comment by dweomer** [comment]
@amackillop please re-open if disabling spice doesn't fix this for you.
