### ISSUE TITLE
proposal: upgrade controller

### ISSUE THREAD

**Issue by dweomer** [rancher/k3os#253]
Given community contributions #from @bhale and @zimme #219, rancher/k3os#225 we have the beginnings of a real upgrade path. An operator (custom resources + controller) to automate application of these scripts would live up to the promised state of things in the README.

Our custom resource(s) should track:
- [x] (P1) `version` : string (e.g. `VERSION_ID` from `/etc/os-release`)
- [x] (P1) `concurrency` : int (maximum number of upgrading nodes at any one time)
- [x] (P2) `channel` : string (e.g. `edge`, `stable`)
- [x] (P3) `autoUpgrade` : bool (perform upgrades automatically)

While there are three distinct artifacts that k3OS bundles (kernel, k3os, k3) we will focus initially on upgrading the bundle as a whole with the single caveat that upgrading the kernel for overlay installations should be out of scope.

**Comment by zimme** [comment]
Doesn't takeover install use the k3os kernel? I got it in my head that it's only the overlay install that's using it's own kernel?

**Comment by dweomer** [comment]
> Doesn't takeover install use the k3os kernel? I got it in my head that it's only the overlay install that's using it's own kernel?

Good catch @zimme, I've updated the caveat.

**Comment by bhale** [comment]
Since this will be driven by Kube, ergo containers, do we want to keep calling out to the bash code resident on the host, or instead convert the logic into some Go code we could place in a simple binary in a daemonset or job? 

I would be willing to take a pass at converting the upgrade logic to a Go binary.

**Comment by bhale** [comment]
Thinking about something like this - you'll notice a glaring bash-ism but I'm not sure it's a deal breaker. Looking for input on how the | tar behavior could be achieved in pure Go. 

https://gist.github.com/bhale/1618ccd634d7600f8b87cb294e75d107

**Comment by zimme** [comment]
> While there are three distinct artifacts that k3OS bundles (kernel, k3os, k3) we will focus initially on upgrading the bundle as a whole with the single caveat that upgrading the kernel for overlay installations should be out of scope.

I understand the thinking here but, just thinking out loud here, if we were to create a controller for tracking and upgrading each artifact separately or at least 2 controllers one for k3s and one for k3os and kernel, I could see the k3s upgrade controller being useful for people not using k3os and just using k3s on another system.

Thoughts?

**Comment by bhale** [comment]
I'm not sure how reliable a k3s upgrade controller would be to get right on random distributions - right now the installer has a lot of special handling for different init systems. We could assume that an upgrade is just dropping in a new 'k3s' binary every time, but that doesn't give folks an opportunity to benefit from updates to the k3s installer and all the other things it does. 

Also, I *typically* want to consume k3s as part of a k3os vetted release bundle anyways - I only upgrade it out of band as a contributor or someone who really wants to be on the bleeding edge sometimes.

**Comment by zimme** [comment]
Yeah, this suggestion came foremost from the not using k3os perspective and if that's not a value add at this point I'd say let's skip it.

Could a k3s upgrade controller in the future potentially use the k3s installer?

**Comment by bhale** [comment]
Yeah, I could see that could see that being be pretty cool for non-k3os folks.

**Comment by bhale** [comment]
Another minor thing coming to mind, if I run my server component of k3os with --skip-agent, and I run this upgrade controller as a daemonset (just for argument's sake), how will I ever get the pod scheduled on the server node?

**Comment by dweomer** [comment]
> Since this will be driven by Kube, ergo containers, do we want to keep calling out to the bash code resident on the host, or instead convert the logic into some Go code we could place in a simple binary in a daemonset or job?
> 
> I would be willing to take a pass at converting the upgrade logic to a Go binary.

TBD, but the most basic, requisite parts to perform the upgrade(s) are captured there and so I felt it was warranted to call them out in a good light.

**Comment by dweomer** [comment]
> > While there are three distinct artifacts that k3OS bundles (kernel, k3os, k3) we will focus initially on upgrading the bundle as a whole with the single caveat that upgrading the kernel for overlay installations should be out of scope.
> 
> I understand the thinking here but, just thinking out loud here, if we were to create a controller for tracking and upgrading each artifact separately or at least 2 controllers one for k3s and one for k3os and kernel, I could see the k3s upgrade controller being useful for people not using k3os and just using k3s on another system.
> 
> Thoughts?
> 
> edit:
> The k3s controller could then have a special channel `k3os` that would track the k3s version in k3os.

There have been some discussions along these lines but for now, for the sake of simplicity of support, we will treat the upgrade as a monolith.

**Comment by dweomer** [comment]
Addressed by #353
