### ISSUE TITLE
ship Toolbox (or similar) to allow users to bring their own debugging tools

### ISSUE THREAD

**Issue by bhale** [rancher/k3os#256]
K3OS is a stripped down, immutable operating system offering very few tools beyond busybox and curl. 

This is unquestionably a feature. However, if a user wished to debug processes on the system with tools like tshark, gdb, valgrind, etc, this would require them to build and deploy their own rootfs today to bring their own tools.

In Fedora CoreOS and RHEL they ship a script called Toolbox that gives users a way to manage container environments with their own tools.
https://docs.fedoraproject.org/en-US/fedora-silverblue/toolbox/

Pros: 
- reads a config file to allow you to use any container base
- keeps the state of your container around (a pet container)
- can do things unprivileged if this matches the use case

Cons:
- requires podman, which is not packaged in Alpine today.

**Comment by bhale** [comment]
Something you can do with the included tooling right now...

${runc} image pull docker.io/library/ubuntu:latest
${runc} run --privileged --net-host -t docker.io/library/ubuntu:latest ubuntu bash

**Comment by dweomer** [comment]
@bhale `ctr` looks a multi-call target for `k3s`. see the output from `k3s ctr --version` / `k3s ctr --help`

**Comment by bhale** [comment]
> @bhale `ctr` looks a multi-call target for `k3s`. see the output from `k3s ctr --version` / `k3s ctr --help`

Nice. Fixed that.
