### ISSUE TITLE
Missing mdadm

### ISSUE THREAD

**Issue by sgielen** [rancher/k3os#261]
I have k3os running on a machine which has two disks attached that used to encompass a RAID array. I'd like to reassemble the array in order to attach the storage to my k3s cluster, but `mdadm` does not exist. Should mdadm be added to the k3os base?

Alternatively, I don't believe k3os comes with a package manager; how would you recommend one goes about installing additional dependencies that must run on the host?

Thanks!

**Comment by sgielen** [comment]
By the way, if you agree that the package should be added to the base distribution, I'd like to do the work to change this issue into a PR. If you could give me some development pointers, I'll come back with a patch :-)

**Comment by dweomer** [comment]
> By the way, if you agree that the package should be added to the base distribution, I'd like to do the work to change this issue into a PR. If you could give me some development pointers, I'll come back with a patch :-)

@sgielen I await your pull-request submission.

**Comment by ibuildthecloud** [comment]
We should definitely have mdadm.

**Comment by bhale** [comment]
@sgielen Take a look at images/00-base/Dockerfile

**Comment by sgielen** [comment]
Thanks @dweomer, I had actually also arrived at the patch in your PR but was having some problems testing it.

While I could build k3os using `scripts/default` successfully, running it using `scripts/run` failed during its run of `scripts/build` with:

```
+ docker build --build-arg TAG=dev --build-arg VERSION=47f442c-dirty --build-arg REPO=rancher --build-arg ARCH=amd64 -f /home/sjors/src/k3os/k3os/images/00-base/Dockerfile -t rancher/k3os-base:dev .
[+] Building 3.8s (4/6)                                                                                                                                                                                   
 => [internal] load build definition from Dockerfile                                                                                                                                                 2.0s
 => => transferring dockerfile: 927B                                                                                                                                                                 0.1s
 => [internal] load .dockerignore                                                                                                                                                                    2.2s
 => => transferring context: 2B                                                                                                                                                                      0.0s
 => ERROR [internal] load metadata for docker.io/library/alpine:3.9                                                                                                                                  1.1s
 => ERROR [1/3] FROM docker.io/library/alpine:3.9                                                                                                                                                    0.2s
 => => resolve docker.io/library/alpine:3.9                                                                                                                                                          0.2s
------
 > [internal] load metadata for docker.io/library/alpine:3.9:
------
------
 > [1/3] FROM docker.io/library/alpine:3.9:
------
rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: `GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files`
```

Also, the actual run of qemu-kvm failed because I was running this on a Xen VM and the hypervisor probably does not allow running further virtualization in the VM, as the `kvm-intel` module was failing to load.

**Comment by sgielen** [comment]
Do you have some documentation on building the arm64 version either within k3s or cross-compiling it from another architecture?
