### ISSUE TITLE
Consider adding htop

### ISSUE THREAD

**Issue by zimme** [rancher/k3os#265]
`htop` is a bit nicer than `top`, would you accept a PR to add it?

**Comment by zimme** [comment]
Slightly related questions, do you see support for a `packages` key in cloud config and have that be installed at boot?

**Comment by bhale** [comment]
It seems like a silly thing, but every time I use 'top' on k3os I wish it was 'htop.'

On the second part, I personally like keeping the filesystem read only and upgrades atomic in nature.
Fedora CoreOS and precursor Atomic have a way to unlock it and use rpm-ostree to install more layers with more RPMs. I think it is way too complicated and love how simple k3os currently is. 

Toolbox could solve for installing a lot of tools if I can figure out how to run it in the host PID namespace. The capability might be there but the docs for 'ctr' are pretty rough.
