### ISSUE TITLE
install.sh doesn't create bootable images

### ISSUE THREAD

**Issue by dxlr8r** [rancher/k3os#288]
Running a successful installation (according to the script):

```
K3OS_DEBUG=true ./install.sh /dev/sdb /home/vagrant/k3os-amd64.iso
```

Then converted it to an image: 

```
qemu-img convert -O vmdk -f raw /dev/sdb /home/vagrant/k3OS.vmdk -o size=2G -o compat6
```

And tested this image in both VMWare and VirtualBox, and they all just show the grub prompt, not the menus. 

Also tried to take the disk image for /dev/sdb and boot from that from a new VM, same result. 

Tried this process with RHEL7, Ubuntu Xenial and OpenSuse 42. 

The image do boot though if I'm using for example _Super Grub2 Disk_ , which also detect the menu entries.

**Comment by dxlr8r** [comment]
Seems like the installatio splits the configuration into: 

```
/boot/grub
/boot/grub2
```

Consolidating the two resulted in a successful boot.

**Comment by dweomer** [comment]
Hi @dxlr8r what is the host operating system that you are invoking `./install.sh` on and what does the grub/grub2 installation look like there?

**Comment by dxlr8r** [comment]
> what is the host operating system that you are invoking ./install.sh on

- RHEL7, CentOS 8 and OpenSuse 42 (also had to symlink grub2-install to grub-install)
- Ubuntu Xenial as well, had a lot of issues there as well, but as I have vagrant I just moved to another distro

> what does the grub/grub2 installation look like there

Here from RHEL7, but same on CentOS 8 and OpenSuse 42. 

```
# ll /mnt/boot/grub*
/mnt/boot/grub:
total 12K
drwxr-xr-x. 2 root root 4,0K nov.  19 17:41 .
drwxr-xr-x. 4 root root 4,0K nov.  19 17:41 ..
-rw-r--r--. 1 root root  827 nov.  19 17:41 grub.cfg

/mnt/boot/grub2:
total 32K
drwxr-xr-x. 5 root root 4,0K nov.  19 17:41 .
drwxr-xr-x. 4 root root 4,0K nov.  19 17:41 ..
drwxr-xr-x. 2 root root 4,0K nov.  19 17:41 fonts
-rw-r--r--. 1 root root 1,0K nov.  19 17:41 grubenv
drwxr-xr-x. 2 root root  12K nov.  19 17:55 i386-pc
drwxr-xr-x. 2 root root 4,0K nov.  19 17:55 locale
```

What distro do you use to build?

**Comment by dweomer** [comment]
@dxlr8r if you change the `grub-install` to `grub2-install` on line 5 of [`install.sh`](https://github.com/rancher/k3os/blob/master/install.sh#L5) does that solve the problem for you?

What you have encountered here is a gap in testing. I think most of the community. including myself, is either doing an arm/arm64 overlay or booting from the ISO (see the [vagrant packer template](https://github.com/rancher/k3os/blob/master/package/packer/vagrant/vagrant.json)).

**Comment by dxlr8r** [comment]
> if you change the grub-install to grub2-install on lines 5 and 195 of install.sh does that solve the problem for you?

Only for the symlinking, but found it easier to do a symlink in my pipeline versus editing the install.sh

> gap in testing

Yes, that was kinda the idea I got as well from looking at the script. We use k3OS for x86 and with VMWare without DHCP, so some tinkering is involved.

**Comment by dweomer** [comment]
I've added some documentation to let people know that this is an outstanding incompatibility with some installations of grub2. If you do not feel that this adequately warns users of the problem please feel free to re-open.
