### ISSUE TITLE
cli: roll multiple project commands into single multi-call k3os

### ISSUE THREAD

**Issue by dweomer** [rancher/k3os#294]
There are multiple commands built from this project (and one from a linuxkit fork) that are written in Go and bundled into the squashfs embedded in the k3os binary. This is a somewhat wasteful duplication of the Go runtime and common code for executables that manage the same system resources. Rolling these into a unified executable should save us some small amount of precious memory while also allowing for an enhanced command-line management/operations experience.

Additionally, consider that:
- `os-config` né `k3os-config` né [`cmd/config/main.go`](https://github.com/rancher/k3os/blob/dc87c78544f5047bb4fa679d004a717aa329334d/cmd/config/main.go) is actually an install operation
- whereas, `ccapply` né [`cmd/ccapply/main.go`](https://github.com/rancher/k3os/blob/dc87c78544f5047bb4fa679d004a717aa329334d/cmd/ccapply/main.go) is a configuration operation

If these are to be rolled up into a single `k3os` executable I propose that we also take the opportunity to correctly name the sub-commands they are to become:
- `k3os install` instead of `os-config` (possibly disabled when `k3os.mode != live`)
- `k3os config` instead of `ccapply`

What's more, we pull in and build two executables from [a fork of the linuxkit project](https://github.com/ibuildthecloud/linuxkit). One of them, `metadata`, is unchanged from upstream whereas `rc.init` (invoked in the `initrd` phase) is customized for k3os. We should roll this `rc.init` into a k3os sub-command if not convert it outright to bash scripts. This will re-home important initialization code to this project.

**Comment by zimme** [comment]
> k3os install instead of os-config (possibly disabled when k3os.mode=live)

Isn't that supposed to be "k3os.mode=disk", i.e. only available for live system to install to disk?

**Comment by dweomer** [comment]
Fixed with an edit. I was thinking [this](https://github.com/rancher/k3os/blob/v0.7.1/overlay/libexec/k3os/live#L3-L13) in my head while writing about the inverse condition.

**Comment by dweomer** [comment]
Addressed via #303
