### ISSUE TITLE
option to set proxy settings for continerd daemon required.

### ISSUE THREAD

**Issue by kunalkushwaha** [rancher/k3os#30]
To download container images, proxy settings are required for running `containerd`.

Typically, if `containerd` service is run with setting, it works for `kubernetes` + `containerd`.
```
[Service]
ExecStart=/usr/local/bin/containerd
Restart=always
Environment="HTTP_PROXY=http://example.com:8080"
Environment="HTTPS_PROXY=http://example.com:8080"
```

cannot find systemd service file for `containerd`. Proxy info can be asked while initial setup and passed while starting `containerd`.

**Comment by kunalkushwaha** [comment]
system wide proxy via `cloud-init` will not work as conflicts with `kubernetes-dns`

**Comment by lianghuiyuan** [comment]
I need set proxy settings too,
and cannot find systemd service file for containerd...

**Comment by pagong** [comment]
k3os is **NOT** based on a classic Linux. Such there is no `systemd` to be configured.

Please have a look at the config options that can be applied during installation:
https://github.com/rancher/k3os#sample-configyaml  and
https://github.com/rancher/k3os#configuration-reference

Good luck.

**Comment by dweomer** [comment]
The k3os init system is a slightly augmented openrc and not in any way compatible with systemd units.

Please see https://github.com/rancher/k3os#k3osenvironment for help with setting proxy values. All `k3os.environment` variables are written to `/etc/environment` which is sourced by the `k3s-service` openrc service prior to starting `k3s` (which is the parent process of `containerd`).
