### ISSUE TITLE
Unable to delete a Dead / Disconnected Node

### ISSUE THREAD

**Issue by jasonbarbee** [rancher/k3os#302]
**Version**
0.70.1 on Server and Agents

**Architecture**
Both sides are x86_64

**Describe the bug**
Unable to delete dead/stale nodes.

**To Reproduce**
Boot up a node, join it to the k3s Master, then destroy it / do not remove it gracefully.

**Expected behavior**
I would expect to be able to delete the node.

**Actual behavior**
``` bash 
k3os-26984 [~]$ sudo kubectl get nodes
NAME          STATUS     ROLES    AGE     VERSION
smarttruck    NotReady   <none>   56m     v1.16.3-k3s.2
smarttruck2   NotReady   <none>   19m     v1.16.3-k3s.2
k3os-26984    Ready      master   2d22h   v1.16.3-k3s.2
smarttruck1   Ready      <none>   33m     v1.16.3-k3s.2
k3os-26984 [~]$ kubectl delete node smartruck
Error from server (NotFound): nodes "smartruck" not found
k3os-26984 [~]$ kubectl delete node smartruck2
Error from server (NotFound): nodes "smartruck2" not found
k3os-26984 [~]$
```
What am I doing wrong?

**Comment by bhale** [comment]
It looks possibly like a typo, as you tried to delete smartruck not smarttruck. Give it a try.

**Comment by jasonbarbee** [comment]
That was it. It's been a long k3os day, remastering ISO a few times till I got it right, and a typo got me at the end. Thanks!
