### ISSUE TITLE
rootfs: update alpine base

### ISSUE THREAD

**Issue by dweomer** [rancher/k3os#304]
**Is your feature request related to a problem? Please describe.**
k3OS is currently based off of alpine 3.9 whereas the latest supported version of alpine is 3.10. this means that 3.9 only gets security updates, no bugfixes.
- see https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases

**Describe the solution you'd like**
The `base` image in the build should `FROM alpine:3.10`

**Describe alternatives you've considered**
n/a

**Additional context**
- https://github.com/rancher/k3os/commit/c1024ec694643a98755a095d0db646183fd82037#commitcomment-35201768

**Comment by phaer** [comment]
The issue described seems to be done already? You, @dweomer [bumped it to 3.11](https://github.com/rancher/k3os/commit/159a17dca60b372bb0c57af6ee32bea97bb34782) which is the current stable release.

**Comment by dweomer** [comment]
Fixed by #332
