### ISSUE TITLE
The OS written by Golang for K3S?

### ISSUE THREAD

**Issue by chalince** [rancher/k3os#31]
The OS written by Golang for K3S?

**Comment by warmchang** [comment]
https://k3os.io/

Wherever possible we built on existing open source Linux distros with proven community support and security focus. **_We use the Ubuntu kernel_** which has excellent up-to-date support for recent kernel versions. We leverage the tooling and packaging of the lightweight Alpine Linux distro.

**Comment by dweomer** [comment]
Adding to what @warmchang has said, we re-use/fork a handful of the linuxkit executables that are written in go.
