### ISSUE TITLE
support trident storage provider from netapp

### ISSUE THREAD

**Issue by dweomer** [rancher/k3os#313]
**Is your feature request related to a problem? Please describe.**
Would like to use NetApp/trident storage provider on k3OS.

**Describe the solution you'd like**
Include these packages in the base build:
- iscsi-scst
- lsscsi
- multipath-tools
- open-iscsi (already installed)

Additionally, make sure the necessary daemons are running:
- iscsid
- multipathd

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by ibuildthecloud** [comment]
Makes sense, just pull in these deps

**Comment by zimme** [comment]
Just a stray thought that hit me looking at this.

If k3os keeps adding deps like this to support potentially a lot of different storage providers and other things k3os will keep growing and people that don't use the specific providers/things don't need these dependencies. Doesn't this kinda validate the scenario of supporting a packages key in cloud-init/package manager to install necessary packages for cases like this while keeping k3os smaller by default?
