### ISSUE TITLE
Missing SFTP binary for OpenSSH server in k3os

### ISSUE THREAD

**Issue by ppmathis** [rancher/k3os#317]
**Version**
v0.7.1

**Architecture**
x86_64

**Describe the bug**
It is currently not possible to connect to k3os using SFTP, as the subsystem in `sshd_config` is set to `/usr/lib/ssh/sftp-server` which simply does not exist on the file system.

**To Reproduce**
Install a new copy of k3os, ensure that SSH access works and attempt to use `sftp` for connecting to k3os. The connection will fail with exit code 127 due to the missing SFTP server binary.

**Expected behavior**
Especially for small or test environments without any GitOps integration it seems useful to have working SFTP for transferring files easily to the k3os installation. Given the fact that the SFTP subsystem is not explicitly disabled and instead points to a missing binary, this seems more like a bug than a feature request to me.

**Actual behavior**
It should be possible to connect to the k3os instance using SFTP.

**Additional context**
The issue seems fairly simple to fix, as OpenSSH nowadays ships an internal SFTP server, which can be enabled by replacing `Subsystem sftp /usr/lib/ssh/sftp-server` with `Subsystem sftp internal-sftp` in `/etc/ssh/sshd_config`. This has been successfully tested by me, but these changes are obviously ephemeral.

**Comment by dweomer** [comment]
@ppmathis I see that Alpine (where we source most of our rootfs from) has available the `openssh-sftp-server` package that we aren't installing. Would modifying the base/rootfs image during build to include this package (which installs one file, `usr/lib/ssh/sftp-server`) satisfy your use case in an acceptable manor or is the `internal-sftp` subsystem to be favored?

**Comment by dweomer** [comment]
Ah, this seems relevant and helpful: https://serverfault.com/questions/660160/openssh-difference-between-internal-sftp-and-sftp-server

**Comment by ppmathis** [comment]
> @ppmathis Would modifying the base/rootfs image during build to include this package (which installs one file, `usr/lib/ssh/sftp-server`) satisfy your use case in an acceptable manner or is the `internal-sftp` subsystem to be favored?

Thank you for your quick reply. As you've already discovered, the two options (`internal-sftp` and `sftp-server`) are pretty similar and don't make any difference in most use cases, so I leave that decision up to you. I'm running `internal-sftp` since years on many standalone Debian servers without any issues, so I suppose this would be the best pick for k3os as it is the modern approach and does not require any additional files.

**Comment by dweomer** [comment]
@ppmathis BTW, until this is addressed directly (I may try to squeeze in to a release today included with an updated kernel) a suitable `boot_cmd` entry in your `config.yaml` can be used to mutate/correct the default sshd config. Your changes are still technically ephemeral this way but at least they get applied at every boot.

**Comment by ppmathis** [comment]
Thank you very much once again, I can confirm that SFTP is working out of the box in v0.8.0! :tada:
