### ISSUE TITLE
Your Getting Started link does not give information on how to get started.

### ISSUE THREAD

**Issue by paul-hammant** [rancher/k3os#32]

**Comment by florianb** [comment]
Agreed - looking forward to take first steps and - if possible - contribute.

**Comment by nstielau** [comment]
Yes, in particular how the github login integration works (which seems like a cool feature) or how to set up basic user login post-install.

**Comment by tfiduccia** [comment]
Quick Start & Installation information/Configuration has been updated in the readme.
