### ISSUE TITLE
build and publish containers images for various bits of the project

### ISSUE THREAD

**Issue by dweomer** [rancher/k3os#324]
**Is your feature request related to a problem? Please describe.**
k3OS is built from a number of sources from the internet other than just this repository. These resources are pulled in at build time and a number of such are specified by download URL. These download URLs make the build somewhat hard to parameterize without editing the project in place. For many scenarios this isn't overly burdensome but taking the `k3s` dependency as an example and this PR: rancher/k3s#1171. There is currently no way to test this in k3OS without some severe local mangling where sourcing the bits for `k3s` to test this integration could be as simple as passing a build parameter that specifies a local `k3s` image.

Additionally, a `rancher/k3os:v1.2.3` container is an easily verified/validated source of upgrade artifacts.

**Describe the solution you'd like**
Build and publish container images.

**Describe alternatives you've considered**
Well, we could continue to orchestrate everything locally into a limited number of binaries but forces us to either rely on github for release distribution infrastructure or we roll our own. Container registries are easy to run and we can even distribute all-in-one k3OS bits + registry to run in air-gapped installations which limits the out-of-band activities that an operator would need to perform (e.g. download the registry and start it up on the cluster with all nodes configured to treat it as docker.io) to operate a cluster.

**Additional context**
n/a

**Comment by bhale** [comment]
I've wanted to contribute to iterating on the kernel more often, but the startup costs to build the k3os-kernel stage artifacts, host them somewhere, and rewrite the build tools to point to the new location are discouraging for a small change. Making the included batteries as easy to swap as pulling a Docker image would be a most welcome change.

**Comment by dweomer** [comment]
- https://hub.docker.com/r/rancher/k3os
