### ISSUE TITLE
K3OS tries to download GitHub keys over a link-local network

### ISSUE THREAD

**Issue by stellirin** [rancher/k3os#338]
**Version**

`v0.8.0`

**Architecture**

`amd64`

**Describe the bug**

SSH keys fail to load from GitHub, tries to use a local IPv6 address

**To Reproduce**

First reboot after PXE install:
```
ERROR[0010] failed to authorise SSH key github:stellirin: Get https://github.com/stellirin.keys: dial tcp: lookup github.com on [fe80::b6fb:e4ff:fed5:f196]:53: dial udp: [fe80::b6fb:e4ff:fed5:f196]:53: connect: invalid argument
```
**Expected behavior**

* Use a valid network before downloading
* Wait for a valid IPv4 or IPv6 address
* retry download if first attempt fails

**Actual behavior**

k3OS tries to download github keys over a link-local network.

**Additional context**

My network environment is relatively slow to assign an IPv4 address over DHCP, so k3OS detects the mandatory link-local IPv6 address as a valid network and attempts to download.

**Comment by dweomer** [comment]
@stellirin the `k3os config` invocation by the "ccapply" openrc service does make a best effort attempt to download keys from github if a failure is encountered for any reason. This "best effort" is currently 10 retries with a 1 second wait in between.

Determining a "valid network link" is distinctly a local problem and so k3OS makes no such attempt. However, there are a couple of things that you can try to resolve the issue:

### Invoke `k3os config` Once the Link is Available

This can be done as the `rancher` user after login, i.e. `sudo k3os config`. If you need something more automated, you could put this in a script (after some timeout or link availability/correctness check) and drop it in the `/etc/local.d` directory, via `write_files`, and make sure it has a `.start` extension. See the `/etc/local.d/README`:
```
This directory should contain programs or scripts which are to be run
when the local service is started or stopped.

If a file in this directory is executable and it has a .start extension,
it will be run when the local service is started. If a file is
executable and it has a .stop extension, it will be run when the local
service is stopped.

All files are processed in lexical order.

Keep in mind that files in this directory are processed sequentially,
and the local service is not considered started or stopped until
everything is processed, so if you have a process which takes a long
time to run, it can delay your boot or shutdown processing.
```

### Override `/etc/conf.d/net-online`
...via a `write_files` entry in `config.yaml`. here is the default file with hopefully helpful comments:
```
# The interfaces setting controls which interfaces the net-online
# service considers in deciding whether the network is active. The
# default is all interfaces that support ethernet.
#interfaces="eth0 wlan0"

# The minimum_up setting controls how many interfaces the net-online
# service expects to be "up" when deciding whether the network is active.
# The default is the number of detected/specified interfaces.
minimum_up=1

# This setting controls whether a ping test is included in the test for
# network connectivity after all interfaces are active.
#include_ping_test=yes

# This setting is the host to attempt to ping if the above is yes.
# The default is google.com.
#ping_test_host=get.k3s.io

# The timeout setting controls how long the net-online service waits
# for the network to be configured.
# The default is 120 seconds.
# if this is set to 0, the wait is infinite.
timeout=30
```
---

Setting `include_ping_test=yes` via `write_files` or `boot_cmd` will probably get you the most correct results for the effort but be warned that the `ccapply` service has a `want network-online` dependency which means that for as long as your link is unavailable, up to a hard-to-determine multiplicative factor of the timeout, your boot process will be hung waiting on the network. By way of example, when `include_ping_test=yes` and `timeout=30` (which used to be the default) booting air-gapped systems (aka incurring the full timeout) would take from 5 to 7 minutes.

**Comment by dweomer** [comment]
@stellirin were any of the suggestions in my previous comment helpful?

**Comment by stellirin** [comment]
@dweomer I considered some of the suggestions and I appreciate the detail you went to. However I believe the `k3os` distribution is perhaps _too_ minimal as I started hitting other issues besides the two I raised here.

I had already been using `k3s` with RedHat CoreOS without any of the issues I had on `k3os`, so I'm sticking with that for now. I wanted to see if `k3os` would be easier, but with my hardware it was not. https://github.com/stellirin/coreos-k3s-ceph/blob/master/ignition/k3s-agent.yaml

Unfortunately I didn't make notes on the further issues I had.

**Comment by dweomer** [comment]
> @dweomer I considered some of the suggestions and I appreciate the detail you went to. However I believe the `k3os` distribution is perhaps _too_ minimal as I started hitting other issues besides the two I raised here.
> 
> I had already been using `k3s` with RedHat CoreOS without any of the issues I had on `k3os`, so I'm sticking with that for now. I wanted to see if `k3os` would be easier, but with my hardware it was not. https://github.com/stellirin/coreos-k3s-ceph/blob/master/ignition/k3s-agent.yaml
> 
> Unfortunately I didn't make notes on the further issues I had.

Closing this for now but if you take it up again @stellirin please feel free to re-open. Any notes that you have on your use-case and how k3OS made it difficult/impossible to implement would be welcome. Feel free to ping me on the #k3os channel on https://rancher-users.slack.com
