### ISSUE TITLE
Removal of linuxkit hostname causes issues

### ISSUE THREAD

**Issue by Kampe** [rancher/k3os#342]
**Version**
0.8.0

**Architecture**
creation of n agents will cause issues

**Describe the bug**
On node creation, if a hostname is not specified localhost is assumed, which causes issues when any more agents come online using the same hostname

**To Reproduce**
start a server and spin up two agents without hostnames

**Expected behavior**
Utilize linuxkit randomized hostname

**Actual behavior**
hostname is set to localhost

**Comment by dweomer** [comment]
@Kampe can you specify whether you're running on am64, arm64, or arm? Normal install, takevoer, or overlay?

**Comment by Kampe** [comment]
sorry! normal install on amd64, iso boot via USB
