### ISSUE TITLE
using wget results in TLS connect failed

### ISSUE THREAD

**Issue by dlannan** [rancher/k3os#344]
**Version**
v0.8.0

**Architecture**
x86_64

**Describe the bug**
When calling wget for various urls (I have mostly been trying your github repos) it reports:
Connecting to github.com (xxx.xxx.xxx.xxx)
ssl_client: github.com: TLS connect failed
wget: error getting response: Connection reset by peer

**To Reproduce**
sudo wget https://github.com/rancher/k3os/README.md

**Expected behavior**
Fetches the requested file.

**Actual behavior**
Errors.

**Additional context**

**Comment by dlannan** [comment]
Note: I have tested on other OS's (Ubuntu and Solus) and they work fine on the same machine with the same network connectivity.

**Comment by dweomer** [comment]
This is due to busybox wget not using the `/etc/ssl/certs/ca-certificastes.crt` and instead expecting it at `/etc/ssl/cert.pem`.
