### ISSUE TITLE
Unable to image bare metal from USB drives

### ISSUE THREAD

**Issue by joharper54SEG** [rancher/k3os#358]
**Version**
v0.7.1
v0.8.0
v0.9.0-rc1

**Architecture**
x86

**Describe the bug**
Booting a bare metal device from a USB key made from the ISO image fails to install k3os.  Error is thrown when trying to mount disks.

![k3os-error1](https://user-images.githubusercontent.com/46793278/73212457-49b96d00-411c-11ea-8d92-518e40cfed20.jpg)
![k3os-error2](https://user-images.githubusercontent.com/46793278/73212469-4cb45d80-411c-11ea-9746-22010a3ddd80.jpg)

**To Reproduce**
Write ISO image to USB drive and boot.  Try and run k3os install.

I have been writing the USB drives from a windows machine using Rufus in DD mode.  This used to work but started to fail.  Tried to write the drive from ubuntu using dd and it won't boot at all, gives an error that is can't find the kernel.

This behavior is only happening on bare metal when trying to use a USB drive to install.  I was able to successfully image the device from a portable USB DVD Drive using the same ISO burned to DVD.  Mounting the ISO to a VM also works fine.

v0.6.0 is the only working ISO for bare metal.  Something changed after this version that broke bare metal installs from USB.

**Expected behavior**
k3os should format the disk and install

**Comment by dweomer** [comment]
@joharper54SEG  there might be an issue with how we are creating the ISO image but I just flashed it to USB using BalenaEtcher on macOS and it worked without issue on a NUC7i5BNK. I did have a false start when accidentally selecting the non-UEFI USB boot option,  however, so depending on your hardware make sure you select the correct boot option.

**Comment by joharper54SEG** [comment]
I found a mac to use and flashed with BalenaEtcher just to make sure we are on the same page.  The ISO downloaded from github flashed fine with no errors.  My refactored ISO is failing with the same error.  So it appears that something in the refactoring process is producing an ISO that is not quite right.

My build pipeline has the following tasks to create my custom ISO.
wget $(k3os.release.uri)
mkdir source
mkdir -p newiso/boot/grub
sudo mount -o loop k3os-amd64.iso source
sudo cp -rf source/k3os newiso/
sudo cp -f configs/config.yaml newiso/k3os/system/config.yaml
sudo cp -f configs/grub.cfg newiso/boot/grub/grub.cfg
grub-mkrescue -o k3os-seg.iso newiso/ -- -volid K3OS

**Comment by dweomer** [comment]
> I found a mac to use and flashed with BalenaEtcher just to make sure we are on the same page. The ISO downloaded from github flashed fine with no errors. My refactored ISO is failing with the same error. So it appears that something in the refactoring process is producing an ISO that is not quite right.
> 
> My build pipeline has the following tasks to create my custom ISO.
> wget $(k3os.release.uri)
> mkdir source
> mkdir -p newiso/boot/grub
> sudo mount -o loop k3os-amd64.iso source
> sudo cp -rf source/k3os newiso/
> sudo cp -f configs/config.yaml newiso/k3os/system/config.yaml
> sudo cp -f configs/grub.cfg newiso/boot/grub/grub.cfg
> grub-mkrescue -o k3os-seg.iso newiso/ -- -volid K3OS

This looks compatible with the ["Remasering ISO" guidance](https://github.com/rancher/k3os#remastering-iso). Are you by chance running these commands from a centos/rhel linux box? If so you might be running into #288

**Comment by joharper54SEG** [comment]
I am using ubuntu on the build machines.  I have tried ubuntu 16.04 and k3os fails to boot, errors out and dumps me into grub rescue.  Ubuntu 18.04 is producing the ISO with the mounting issues.

**Comment by joharper54SEG** [comment]
I was able to work around this by rebuilding from source like we did for #203 rather than refactoring the ISO.  It takes a little longer but does produce a working customized ISO at then end.

`mkdir $(Build.SourcesDirectory)/k3os
git clone --single-branch --progress -b v0.8.0 "https://github.com/rancher/k3os" $(Build.SourcesDirectory)/k3os

cp -f $(Build.SourcesDirectory)/configs/grub.cfg $(Build.SourcesDirectory)/k3os/images/07-iso/grub.cfg
cp -f $(Build.SourcesDirectory)/configs/config.yaml $(Build.SourcesDirectory)/k3os/images/07-iso/config.yaml
cd $(Build.SourcesDirectory)/k3os

make`

**Comment by dweomer** [comment]
> I was able to work around this by rebuilding from source like we did for #203 rather than refactoring the ISO. It takes a little longer but does produce a working customized ISO at then end.
> 
> `mkdir $(Build.SourcesDirectory)/k3os
> git clone --single-branch --progress -b v0.8.0 "https://github.com/rancher/k3os" $(Build.SourcesDirectory)/k3os
> 
> cp -f $(Build.SourcesDirectory)/configs/grub.cfg $(Build.SourcesDirectory)/k3os/images/07-iso/grub.cfg
> cp -f $(Build.SourcesDirectory)/configs/config.yaml $(Build.SourcesDirectory)/k3os/images/07-iso/config.yaml
> cd $(Build.SourcesDirectory)/k3os
> 
> make`

@joharper54SEG excellent, I am glad you were able to find a workaround.

I think the problem with the Remastering ISO guidance, as per #288, is that it doesn't call out that `grub-mkrescue` on some( many?) systems creates `/boot/grub2` instead of the expected `/boot/grub`.

**Comment by dweomer** [comment]
@joharper54SEG I have added some documentation to the readme to warn users `grub-mkrescue` sometimes creates `${ISO}/boot/grub2` instead of `${ISO}/boot/grub`. If it turns out that this was not the problem and/or your workaround isn't viable long-term, please re-open this issue or submit another.

**Comment by iJebus** [comment]
Just an FYI that I'm seeing this same issue with v0.10.0 k3os and v1.5.80 BalenaEtcher running on a Windows 10 host.

**Comment by lcotonea** [comment]
Another [quick & dirty] solution is to change usb devices location on the server (usb devices permutation or use another free usb location) and reboot. Some times it works.
