### ISSUE TITLE
Installation does not boot

### ISSUE THREAD

**Issue by Remarknl** [rancher/k3os#366]
I am trying to install k3os on an HP T620 thin client. Booting from usb works fine but after reboot the device says that no boot device has been detected. I tried using stable and rc1. Both the same result.
I also tried installing vanilla alpine linux. Alpine has the same error. The only difference is that alpine provides another "UEFI" entry in the bootable devices. Disabling the normal "alpine" boot entry allows the system to boot succesful.

Using the rEFInd bootmanager from USB also allows me to boot k3os normally.

What is k3os missing that causes this behaviour?

**Comment by dweomer** [comment]
@Remarknl I haven't booted Alpine in a while (and I do not have the hardware that you do) but I can flash the media to USB and try booting on a NUC7i5BNK to see if I can witness behavior analogous to what you are describing. It might be helpful if you could take some pics with your phone of these boot menus and attach them to comment(s) here.

That said, I have recently installed k3OS v0.9.0-rc2 via flashing the ISO to USB media and with the NUC I have to select the UEFI boot menu option to get a successful install. Is the UEFI boot menu option not available for you on your hardware with the k3OS ISO on USB?

**Comment by Remarknl** [comment]
Thanks for the quick response @dweomer !

This is the boot menu after installing k3os:
![photo5877578640982651620](https://user-images.githubusercontent.com/2486040/73394522-158daa00-42de-11ea-8611-7ea79f036589.jpg)

And this is the boot menu after installing alpine extended 3.11:
![photo5877578640982651621](https://user-images.githubusercontent.com/2486040/73394537-1c1c2180-42de-11ea-86f8-4825560b2dfb.jpg)

So in both cases the option called "alpine" is the default and in both cases that option wont boot. But the extra option that is present with the vanilla alpine install does boot. I can go into the bios and disable the "alpine" option. That way the system will pick the "UEFI: Sandisk" option and booting is succesful.

I am a total newbie when it comes to the boot process of a PC, but i will do what I can. I plan to compare partitions and filesystems this week. I will also compare the contents of /boot/ between the two.

**Comment by Remarknl** [comment]
I found a workaround which seems to work, but i don't understand why.

First i noticed that alpine has:
/boot/efi/EFI/alpine/grubx64.efi
/boot/efi/EFI/boot/bootx64.efi

While k3OS only has EFI/alpine/grubx64.efi

To get it to boot i did the following:
```
mkdir /home/rancher/efi
mount /dev/sda1 /home/rancher/efi
cd /home/rancher/efi/EFI
mkdir boot
cp alpine/grubx64.efi boot/bootx64.efi
```

this only worked after i put the "alpine" boot entry first.

I will try to find a more elegant solution and maybe even a concrete fix.

**Comment by thebiss** [comment]
Thanks for the tip @Remarknl .  A script in cloud config can automatically fix this on first boot.  Inspired by the static IP tip in https://github.com/rancher/k3os/issues/68#issuecomment-492089070

```
write_files:
- encoding: ""
  content: |-
    #!/bin/bash
    write_log (){
        logger -t "${0}" "${1}" && echo "${1}"
    }
    write_log "Verifying EFI boot workaround on vda1"
    mountpoint="/boot/efi"
    trap 'umount "${mountpoint}"' TERM EXIT
    mount /dev/vda1 "${mountpoint}" || write_log "Failed: Could not mount EFI partition."
    [ -r "${mountpoint}/EFI/boot/bootx64.efi" ] && write_log "bootx64.efi already found. " && exit
    mkdir -p "${mountpoint}/EFI/boot" && \
      cp "${mountpoint}/EFI/alpine/grubx64.efi" "${mountpoint}/EFI/boot/bootx64.efi" && \
      write_log "bootx64.efi created." && \
      exit
    write_log "Failed: Could not create bootx64.efi from grubx64.efi."
  owner: root:root
  path: /etc/run-fix-efi-boot.sh
  permissions: '0755'
run_cmd:
- "/etc/run-fix-efi-boot.sh"
```

**Comment by todaywasawesome** [comment]
Just want to leave a breadcrumb for those trying to follow.

The AtomicPi doesn't see the EFI partition that k3os creates. Following the advice here https://github.com/rancher/k3os/issues/366#issuecomment-581137036 will fix it and make it bootable. 

The AtomicPi uses a American Megatrends bios version 2.18.1263 and requires an EFI partition to have a boot/bootx64.efi file set.

**Comment by cdeadspine** [comment]
Watch out for hardware made around the year 2012: apparently they were shipping computers out (acer for sure) that "supported UEFI" but did not support "secure boot" yet. (and latest BIOS never fixed this)

This manifests as : k3os will boot into LIVE mode ok, and appear to install properly, but will never boot from the hard drive

**Comment by Remarknl** [comment]
I think i am going to close this issue. For me it still doesn't fully work. I need to change the boot order in the BIOS after each reinstall. But this is not an issue with k3os. I cannot reproduce the original issue on 4 machines.

Thanks for all the help!
