### ISSUE TITLE
Since version 0.9.0 it is not possible to reinstall a worker node: 

### ISSUE THREAD

**Issue by amiga23** [rancher/k3os#372]
**Is your feature request related to a problem? Please describe.**
Not sure, if this is a bug or a feature.
With version 0.8.0 it was possible to simply wipe the harddisk and restart the installation process. The worker did automatically reregister and would continue as before.
With 0.9.0-rc5 this is not possible anymore. k3s-service stops with the error message:
`"Node password rejected, duplicate hostname or contents of '/etc/rancher/node/password' may not match server node-passwd entry, try enabling a unique node name with the --with-node-id flag"`
Also when deleting the node does not help.
`kubectl delete node worker03`
I could use the --with-node-id flag, but then the nodes get a random suffix.

**Describe the solution you'd like**
Some mechanism to recreate a node with the same name and IP, for example in case of disaster recovery.

**Describe alternatives you've considered**
Alternative solutions could be some command to delete the node fully from the "memory of k3s".

**Additional context**
n/a

**Comment by dweomer** [comment]
@amiga23 I believe that this is expected behavior with the newer version of k3s in scope. Does a wipe and re-install (retaining node name/id) work if you retain `/etc/rancher` and `/var/lib/rancher` and overlay those prior to starting k3s?

**Comment by amiga23** [comment]
The node can be deleted from /var/lib/rancher/k3s/server/cred/node-passwd and then it is possible to register a fresh node with the same name.
This is sufficient for me.
Backing up /etc/rancher and/or /var/lib/docker does not make sense to me, as the advantage of k3os would be lost.
