### ISSUE TITLE
0.9.0-rc5 traefik can not be deployed "unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request"

### ISSUE THREAD

**Issue by amiga23** [rancher/k3os#374]
**Version**
v0.9.0-rc5

**Architecture**
x86_64

**Describe the bug**
Traefik can not be deployed "unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request".
I guess the issue is that the API is not beta anymore and was renamed?

**To Reproduce**
Install a new Virtual Machine with k3os 0.9.0.
Did work well with 0.8.0

**Expected behavior**
Traefik should be installed after creating a standalone k3os kubernetes.

**Actual behavior**
helm-install-traefik pod fails with error:
"unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request"

**Additional context**
If you could give a hint or documentation to understand how the chart is provisioned into the iso, I could try to fix it myself and provide pull-request.
Anyway I am not a fan of Helm and would prefer deployment with kustomize (now also included in kubectl), as it is much better (human-) readable and more clear what happens.

**Comment by amiga23** [comment]
Issue must be something else:
`$ kubectl get --raw /apis/metrics.k8s.io/v1beta1
Error from server (ServiceUnavailable): the server is currently unable to handle the request
`

**Comment by dweomer** [comment]
@amiga23 how are you running k3OS? Installation that was installed from ISO or something else? If you are running with an overlay installation please provide the kernel that you are running with.

**Comment by amiga23** [comment]
Seems to be an issue with multimaster. If I install a single instance, master and agent in one, without any k3s_args, it works fine. But when installing multi-master with dqlite, with 3 masters and 1 worker, the metricsserver is not reachable via api but does also not show an error.

**Comment by amiga23** [comment]
Okay, my mistake, sorry:
time="2020-02-07T08:41:39.954556606Z" level=error msg="--disable-agent is not compatible with dqlite"

**Comment by modzilla99** [comment]
Might be worthwhile to update the documentation to point that out (or add an external database in the sample). I was using it as a blueprint to deploy my server. Guess what the helm didn't work... :P
I am new to kubernetes so that would definately help me and I guess a lot of other people as well.
