### ISSUE TITLE
Hyper-V tools missing (hv_kvp_daemon)

### ISSUE THREAD

**Issue by JT-IT** [rancher/k3os#380]
The hv_kvp_daemon appears to be missing from the k3os installation, but it existed in the RancherOS v1.5 image.  This results in Hyper-V not being able to access the IP address of the guest VM, as well as packer builds hanging on "waiting for SSH to be available".
You can see below, the "IP Address" column in the Hyper-V console is typically populated with an IP address, and it is not.  I see none of the Hyper-V tools running from `services --list` either.
![image](https://user-images.githubusercontent.com/38433978/74781429-753cfc80-526f-11ea-8f3f-fbb859de0e62.png)

**Comment by arlyon** [comment]
Some documentation on the state of hyper-v support would be very useful.
