### ISSUE TITLE
Silent install cannot resolve host for ISO file download

### ISSUE THREAD

**Issue by Raqbit** [rancher/k3os#386]
**Version (k3OS / kernel)**
**k3OS**: `k3os version v0.9.0`
**Kernel**: `5.0.0-37-generic #40~18.04.1 SMP Wed Jan 15 04:09:29 UTC 2020`

**Architecture**
`x86_64`

**Describe the bug**

When starting k3OS with the `k3os.install.silent=true` kernel option, the installer sometimes fails to resolve the host of the provided url for the ISO file (`k3os.install.iso_url`). After executing `sudo k3os install` in the interactive shell, the installation is able to start normally.

```
Running k3OS configuration
mount: /run/k3os/iso: wrong fs type, bad option, bad superblock on /dev/vda, missing codepage or helper program, or other error.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0curl: (6) Could not resolve host: github.com
ERRO[0005] exit status 6
```

**To Reproduce**

k3OS Config:

(You'll probably want to use your own ssh key)

```yaml
ssh_authorized_keys:
- github:raqbit

k3os:
  k3s_args:
  - server
  - "--no-deploy"
  - "traefik"
```

Start script:

(You'll probably need to change the config url)

```sh
kernel=https://github.com/rancher/k3os/releases/download/v0.9.0/k3os-vmlinuz-amd64
initrd=https://github.com/rancher/k3os/releases/download/v0.9.0/k3os-initrd-amd64
kernel_args='console=ttyS0 loglevel=4 k3os.mode=install k3os.install.silent=true k3os.install.device=/dev/vda k3os.install.config_url=http://192.168.122.1:5000/config.yaml k3os.install.iso_url=https://github.com/rancher/k3os/releases/download/v0.9.0/k3os-amd64.iso'

virt-install \
	--connect qemu:///session \
	--name k3os \
	--disk path=./k3os.qcow2,size=8 \
	--ram 2048 \
	--vcpus 1 \
	--os-type linux \
	--os-variant ubuntu18.04 \
	--graphics=none \
	--network bridge=virbr0 \
	--install kernel=${kernel},initrd=${initrd},kernel_args_overwrite=no,kernel_args="${kernel_args}"


```

**Expected behavior**
I expect the installer to only execute once the machine is connected to the network.

**Actual behavior**
The installer tries to download the ISO file but fails because of a DNS resolving issue.

**Comment by dweomer** [comment]
This is likely due to a race-condition with the `connman` service setting up the network. The `net-online` service is there and run but it doesn't check for connectivity by default. This can be achieved with only kernel parameters, e.g. something like:
```
boot_cmd="echo include_ping_test=yes>>/etc/conf.d/net-online boot_cmd="echo ping_test_host=github.com>>/etc/conf.d/net-online"
```

**Comment by erkki** [comment]
Hitting into this race condition as well, fairly consistently. In my case with a curl failure to download the iso.

Could we additionally do a bounded retry loop anywhere curl gets used?

**Comment by Shifter2600** [comment]
@erkki I as well have this same issue and "ERRO[0005] exit status 6" Can we get this added so that my bare-metal k3os install doesn't hit this error?
