### ISSUE TITLE
after install on disk logon with rancher user des not work

### ISSUE THREAD

**Issue by mkostersitz** [rancher/k3os#41]
I booted from ISO
logged in with rancher
ran sudo os-config
stepped through the questions with default answers
ejected the ISO
rebooted the VM

Now unable to login with rancher as the user.

**Comment by huanga** [comment]
Similar to RancherOS, the rancher login is only valid for live CD (or if you added the boot parameter `rancher.password=rancher`). For installing to disk, you need to use cloud-init.yml to add your authorized ssh key under "ssh_authorized_keys" :

```
ssh_authorized_keys:
  - ssh-rsa AAAA1........ user@machine
  - ssh-rsa AAAA2....... anotheruser@machine
```
