### ISSUE TITLE
[Question] support ip change

### ISSUE THREAD

**Issue by dorsany** [rancher/k3os#419]
**Is your feature request related to a problem? Please describe.**
First, today we ship k8s cluster that was installed in the lab to developers. The thing is that now the k8s is located in a different network and I have to change the ip - can be related also to ship k8s cluster to a customer..

Second, k8s cluster that is connected to a dhcp server and after reboot the cluster IP can be changed

**Describe the solution you'd like**
Support ip changes

**Additional context**
I Know that `k3s` support ip changes so just need to be able to configure dhcp nic on the `k3os` and somehow the k3s should detect ip changes and reset itself the ip

Do you plan to support this?

**Comment by dorsany** [comment]
Connectivity issue between pods
Connectivity issues with ingress from external to internal services
Connectivity issue between nodes
And more..

Do you plan to determine that k3os can support only static ips or will it support dhcp also?

**Comment by dweomer** [comment]
> Connectivity issue between pods
> Connectivity issues with ingress from external to internal services
> Connectivity issue between nodes
> And more..
> 
> Do you plan to determine that k3os can support only static ips or will it support dhcp also?

k3OS uses DHCP by default, via connman, unless overridden at boot-time via `write_files` (or the like) in `config.yaml`.

Can you share a minimal set of steps to reproduce the issue(s) you are seeing? I believe that k3s should tolerate dynamic IPs but it is possible you are running into an issue with k3s itself (k3OS shouldn't be getting in the way here).

**Comment by dorsany** [comment]
I'm sure that it's related to k3s itself
But you answered my question about the dhcp
Thanks
