### ISSUE TITLE
udev symlinks are missing

### ISSUE THREAD

**Issue by dweomer** [rancher/k3os#426]
Symlinks such as `/dev/disk/by-{id,label,uuid}` are missing after boot. They do show up after login and manually run the `/etc/init.d/udev-trigger` coldplug init:
- `udevadm trigger --type=subsystems --action=add`
- `udevadm trigger --type=devices --action=add`

**Comment by jdmarble** [comment]
I'm having this problem with v0.19.4-dev.5 . No symlinks under `/dev/disk/` until I manually run `udevadm trigger ...` as described here. The files from #427 are present. I'm more of a systemd person, so I'm not sure how to debug. :)
I'll try with v0.11.1.

**Comment by USA-RedDragon** [comment]
Just faced this on v0.19.5-rc.1 as well, though the symlinks definitely showed up prior to a node reboot.
