### ISSUE TITLE
example config.yaml creates /etc/rc.local that does not get executed

### ISSUE THREAD

**Issue by shir474** [rancher/k3os#430]
**Version (k3OS / kernel)**
k3os version v0.9.1

**Architecture**
x86_64

**Describe the bug**
documentation error: example config.yaml creates /etc/rc.local that doesn't get executed
OpenRC uses /etc/local.d
i.e. https://wiki.gentoo.org/wiki//etc/local.d

**To Reproduce**
write_files:
- content: |
    #!/bin/bash
    echo hello
  owner: root:root
  path: /etc/rc.local
  permissions: '0755'

**Expected behavior**
example should work and execute rc.local

**Actual behavior**
does not execute rc.local

**Additional context**
the file path should be /etc/local.d/example.start
e.g.

write_files:
- content: |
    #!/bin/bash
    echo hello
  owner: root:root
  path: /etc/local.d/example.start
  permissions: '0755'

**Comment by dweomer** [comment]
Thanks @shir474. I haven't reviewed that part of the README.md in some time. This explains why I have had to explain a number of times in various submitted issues why /etc/rc.local doesn't work =)
