### ISSUE TITLE
config.yaml write_files does consistently work

### ISSUE THREAD

**Issue by gbarton** [rancher/k3os#438]
**Version (k3OS / kernel)**
k3os version v0.10.0
5.0.0-43-generic #47~18.04.1 SMP Wed Apr 1 16:27:01 UTC 2020

**Architecture**
x86_64

**Describe the bug**
Much of anything past the sample write_files in README.md causes inability to ssh into the k3os box.  Example config.yaml below to test with.  Box will boot, see the k3os splash, but unable to login to box with provided sshkey.  Also no evidence of errors or logs or failure conditions found in the boot log, so any errors are probably being silently eaten.

**To Reproduce**
I use this script in cloud init once I have booted an ubuntu 18.04 AMI in aws, then reboot the node and attempt to login via ssh with key.  Removing the write_files section allows logging in as expected.  YAML validated as good via http://www.yamllint.com/, script can be pasted onto an already running k3os in /tmp and executes fine.

```
#!/bin/bash

set -e

# This script installs K3os ontop of whatever OS is currently running
# afaik this is the only way to bootstrap a cloud ami, which is to takeover an existing one
# Tested against an ubuntu 18.04 AMI and works well

# references
# k3os https://github.com/rancher/k3os#quick-start
# k3s https://rancher.com/docs/k3s/latest/en/installation/install-options/
# containerd https://blog.scottlowe.org/2020/01/25/manually-loading-container-images-with-containerd/

cat <<EOF > /tmp/config.yaml
# host configs
ssh_authorized_keys:
 # athena config
 - ssh-rsa xxxx
write_files:
- encoding: ""
  content: |-
    #!/bin/bash
    ACCT="$(curl --max-time 10 -s 169.254.169.254/latest/dynamic/instance-identity/document | jq -r '.accountId')"
    re='^[0-9]+$'
    if ! [[ "$ACCT" =~ $re ]]; then
      echo "not a number, must not be aws";
    else
      echo "yup, in cloud"
    fi
  owner: root
  path: /etc/check.sh
  permissions: 0700

# k3os configs
k3os:
  data_sources:
  - aws
  k3s_args:
    - server
    - "--no-deploy=traefik"
    # does not work, have to use containerd
    #- "--docker"
EOF

#K3OS_VER="v0.9.1"
K3OS_VER="v0.10.0"

# get rancher install script
wget https://raw.githubusercontent.com/rancher/k3os/${K3OS_VER}/install.sh
chmod +x install.sh

# figure out the drive that we are overwriting onto
# just finding what root '/' is mounted to
INSTALL_DRIVE=$(df -h | grep "\s/$" | cut -d ' ' -f1)

sudo ./install.sh --takeover --debug --tty ttyS0 --config /tmp/config.yaml --no-format "${INSTALL_DRIVE}" https://github.com/rancher/k3os/releases/download/${K3OS_VER}/k3os-amd64.iso

# Dont forget to reboot the machine now so it can finish the install, then create ami from it
```

**Expected behavior**
file was written to disk and executed, host booted successfully and able to login.

**Actual behavior**
machine seems to fail finalizing the config and I'm guessing never gets to the part that lands the ssh key

**Additional context**
I have a bunch of hardening/OS tweaking that I need to do to the image, was attempting to do it via write_files and do it post setup if you will.  Grabbing the AWS metadata is just a snippet that actually fails the OS in some way that shows inability to login.  I haven't dug into the install/building process enough yet to understand how to make those changes farther upstream but eventually will so I can further lock down device mounting options for example.

**Comment by dweomer** [comment]
> ```yaml
> k3os:
>   data_sources:
>   - aws
> ```

Is it possible that there is user-data that k3OS cloud-config is picking up that could be gumming up the works? It treats a shebang as a script and with `source` it from `/run/k3os/userdata`. Anything else is assumed to be k3OS-flavor cloud-config YAML

**Comment by gbarton** [comment]
Thanks for the reply!
That above file is what I paste verbatim into the AWS user-data for the instance to do the takeover.  Without the write_files it works fine.  Do you think something about the write_files section would mess it up?

**Comment by gbarton** [comment]
I just tested instead of putting the above file in the user_data like I usually do I logged into the ubuntu host and ran it after the host booted.  That way user_data was empty.  Same net issue, cannot login to the host with the write_data block in the yaml.

**Comment by dweomer** [comment]
The problem is with the `permissions` on the `write_files`: it should be a string. I was able to test this on a live k3OS system by dropping your `config.yaml` generated from the script at `/var/lib/rancher/k3os/config.yaml` and then running `sudo k3os config --dump` to force the system to parse it but not apply it. The result:
```
ERRO[0000] json: cannot unmarshal number into Go struct field File.writeFiles.permissions of type string 
```

**Comment by gbarton** [comment]
I knew it was something silly!  Thank you.

That command helps a ton btw, will use that for a sanity check from now on.

I haven't messed with packer before, but if it allows me to build an ami without the spin,install,reboot, snapshot cycle I'm all for it!
