### ISSUE TITLE
docker.io/rancher/k3os:latest: not found

### ISSUE THREAD

**Issue by guiguan** [rancher/k3os#446]
**Version (k3OS / kernel)**
k3os version v0.10.0
5.0.0-43-generic #47~18.04.1 SMP Wed Apr 1 16:27:01 UTC 2020

**Architecture**
x86_64

**Describe the bug**
My `k3os` stopped functioning because `k3os-system/apply-k3os-latest` is stuck on this error:
```
Failed to pull image "rancher/k3os:latest": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/rancher/k3os:latest": failed to resolve reference "docker.io/rancher/k3os:latest": docker.io/rancher/k3os:latest: not found
```

**To Reproduce**
`sudo crictl pull docker.io/rancher/k3os:latest`

**Expected behavior**
without problem

**Actual behavior**
```
FATA[2020-04-25T11:49:45.325673572+10:00] pulling image failed: rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/rancher/k3os:latest": failed to resolve reference "docker.io/rancher/k3os:latest": docker.io/rancher/k3os:latest: not found
```

**Additional context**
Looks like you have forgot to tag the latest image as `latest`

**Comment by dweomer** [comment]
This is because you’ve specified a tag that doesn’t exist as the version for the `k3os-latest` plan? If you want the latest, remove the version on the plan and let the system upgrade controller figure out the latest from the channel (supplied by default).

**Comment by guiguan** [comment]
@dweomer I don't think I have specified a tag anywhere. In `k3os-system/system-upgrade-controller`, there are errors: 

```
system-upgrade-controller E0425 02:07:23.611340       1 controller.go:135] error syncing 'k3os-system/k3os-latest': handler sys │
│ tem-upgrade-controller: Get https://github.com/rancher/k3os/releases/latest: dial tcp: lookup github.com on 10.43.0.10:53: read │
│  udp 10.42.0.77:57031->10.43.0.10:53: i/o timeout, requeuing
```

https://github.com/rancher/k3os/issues/437

**Comment by dweomer** [comment]
> @dweomer I don't think I have specified a tag anywhere. In `k3os-system/system-upgrade-controller`, there are errors:
> 
> ```
> system-upgrade-controller E0425 02:07:23.611340       1 controller.go:135] error syncing 'k3os-system/k3os-latest': handler sys │
> │ tem-upgrade-controller: Get https://github.com/rancher/k3os/releases/latest: dial tcp: lookup github.com on 10.43.0.10:53: read │
> │  udp 10.42.0.77:57031->10.43.0.10:53: i/o timeout, requeuing
> ```
> 
> #437

@guiguan it looks like you are getting closer to the underlying issue. That's a DNS timeout.

**Comment by guiguan** [comment]
@dweomer ohh, probably the `coredns` was not running because the k3os node (single node cluster) was cordoned off by a failure upgrade process. Now, I have removed the `plan.upgrade.cattle.io/k3os-latest` label on the node and did a reboot. The label is set automatically again and everything seems to be working fine. Although, still not sure what's the root cause of the upgrade failure, I know how to recover the error at least. Thank you for your timely replies and help. You can close this issue now.
