### ISSUE TITLE
Trying to Install OpenEBS on Minikube

### ISSUE THREAD

**Issue by vamsijakkula** [rancher/k3os#450]
MountVolume.SetUp failed for volume "udev" : hostPath type check failed: /run/udev is not a directory.
Any idea as how to fix it.

**Comment by dweomer** [comment]
@vamsijakkula this issue title mentions minikube. As far as I can tell minikube utilizes it's own appliance OS with no option to swap out with another. Are you running minikube, or k3OS? If minikube, please see https://github.com/kubernetes/minikube/issues and report your issue there.

If you are running k3OS, can you share the version and architecture (as is prompted for in the bug template)? After moving to udev from mdev in v0.9.0 I did check that OpenEBS installed without issue: https://twitter.com/dweomer/status/1226289185054588933?s=20

**Comment by dweomer** [comment]
Please re-open if you are running k3OS.
