### ISSUE TITLE
Update connman to version 1.38

### ISSUE THREAD

**Issue by CuBiC3D** [rancher/k3os#461]
**Is your feature request related to a problem? Please describe.**
Version 1.37 of connman does not support the `DeviceName` parameter to be set in service config, so matching devices requires to use the MAC address which is unknown on provisioning a new machine.
```
[service_eth0]
DeviceName=eth0
Type=ethernet
IPv4=dhcp
IPv6=2a01:xxx:xxx:xxx::1/64/fe80::1
```
Current version ignores `DeviceName` and sets the IPv6 address for all interfaces found, including eth1 (which is the internal interface in that case)

**Describe the solution you'd like**
This [commit](https://kernel.googlesource.com/pub/scm/network/connman/connman/+/a719719e126407004840e8da3b8139a7cfc98890) introduces `DeviceName` and is dated back to April 2019 

**Describe alternatives you've considered**
Make network configuration simpler with parameters in cloud config files

**Comment by dweomer** [comment]
Our userspace currently comes from Alpine 3.11 which only has connman 1.37. I do see 1.38 on edge which tells me we will likely see it in k3OS when Alpine bumps to 3.12.
