### ISSUE TITLE
ERROR: Module rbd not found.

### ISSUE THREAD

**Issue by nazarewk** [rancher/k3os#493]
**Is your feature request related to a problem? Please describe.**
I want to use Rook's Ceph integration on k3os based Raspberry Pi 4 cluster.
Does not look like i can do that due to missing `rbd` kernel module

**Additional context**
I managed to get up to PV issuing, but getting errors with following errors:
```
MountVolume.MountDevice failed for volume "pvc-297d546b-6c64-462b-bb7a-7063e6fd0f02" : rpc error: code = Internal desc = rbd: map failed exit status 2, rbd output: modinfo: ERROR: Module rbd not found.
modprobe: FATAL: Module rbd not found.
rbd: failed to load rbd kernel module (1)
rbd: sysfs write failed
In some cases useful info is found in syslog - try "dmesg | tail".
rbd: map failed: (2) No such file or directory
```

**Comment by billimek** [comment]
I have the same issue.

It is possible to solve this by installing k3os via the overlay installation on top of a modern kernel with rbd already present. Ubuntu 20.04, for example. However, there appears to be an issue right now with running k3os via overlay so this approach isn’t ideal right now.

**Comment by dweomer** [comment]
I’d be surprised if the rbd module wasn’t compiled. It’s currently the bionic/hwe kernel which means eoan and I think “modern”. It’s possible it isn’t on disk as it should be however. Load the configs module and zcat /proc/config.gz

**Comment by sgielen** [comment]
I have instructions here on compiling the module yourself: https://github.com/sgielen/picl-k3os-image-generator/issues/6#issuecomment-604531224

**Comment by dweomer** [comment]
For `amd64` systems installed from ISO the module is there:
![Screenshot from 2020-05-26 00-10-16](https://user-images.githubusercontent.com/1033444/82870934-97d15800-9ee5-11ea-9a3b-ef5a6d3b2849.png)

Given that RPI is overlay, its a BYO scenario. Glad to see that OpenEBS is filling the gap.

**Comment by nazarewk** [comment]
I'm actually not using overlay installation unless https://github.com/sgielen/picl-k3os-image-generator counts as an overlay.
