### ISSUE TITLE
How to perform backup of master database?

### ISSUE THREAD

**Issue by sgielen** [rancher/k3os#494]
**Is your feature request related to a problem? Please describe.**
I'm running my cluster on a couple of arm64 nodes, and I sometimes want to reinstall them. For example, I've had a bad SD card cause issues, and later a power loss caused a disk corruption. For all worker nodes this is easy to do, but if I do it with my master node, the database of all Kubernetes state will be gone. Any way to get a copy of it that's easy to restore would be wonderful.

**Describe the solution you'd like**
The easiest solution would be to document which directory should be backed up that's guaranteed to contain all k8s state. Then, I could run a CronJob in the cluster that takes a tarball of that directory on the host and copies it somewhere. Perhaps the specification of that CronJob could be added to documentation, to allow others to easily backup as well.

A restore could just be as simple as "in the config.yaml, if the target directory doesn't exist, download the last backup and unpack it into the target directory". Then, at least, the cluster would be immediately back to the last backed up state.

**Comment by dweomer** [comment]
For long-running clusters on RPI I recommend running at least the master with root block device on external SSD/NVMe (e.g. `root=LABEL=K3OS` or the like in your cmdline.txt) but if you must run on MMC and you need to back it up you can mount your rootfs block device, on say `/mnt/`, and then tarball everything under `/mnt/k3os/data`. This is where are persistent changes to the default filesystem(s) land with incoming symlinks being essentially ephemeral. Take care when reconstituting a master node from such a backup as it should have the name node name (typically hostname) as before.

Caveat, I doubt that this is reliable at all for the **experimental** HQ dqlite.

**Comment by sgielen** [comment]
I might try out this generic Kubernetes solution: https://velero.io/docs/v1.4/

It is a piece of software to make a backup of all resources that exist within the cluster, including the data within PVs, and allows restore to a pristine cluster.

**Comment by sgielen** [comment]
With Velero, this seems pretty easily doable.

To install: https://velero.io/docs/v1.4/basic-install/ / https://velero.io/docs/v1.4/customize-installation/

Then, to create a daily backup of all cluster objects excluding volumes:

```
$ velero schedule create clusterstate --schedule="@every 24h" --snapshot-volumes=false --ttl 168h
```

This lists backups:

```
$ velero backup get
NAME                          STATUS      CREATED                          EXPIRES   STORAGE LOCATION   SELECTOR
clusterstate-20200702193354   Completed   2020-07-02 21:33:54 +0200 CEST   6d        default            <none>
```

Then, this should restore the scheduled backup back into an empty cluster:

```
velero restore create --from-schedule clusterstate
```

I haven't tested the restore yet, will do that and report. If the restore works, I consider that an appropriate solution to this issue, and will close it :)

**Comment by t0b3** [comment]
@sgielen what is your experience with the velero restore test?
