### ISSUE TITLE
ISO Grub option to install to disk

### ISSUE THREAD

**Issue by philipsparrow** [rancher/k3os#499]
**Is your feature request related to a problem? Please describe.**
I would like the ISO to make it easier to install to disk. Currently, I need to log in as `rancher` user and then type `sudo k3os install`.

**Describe the solution you'd like**
I would like a separate Grub option to automatically launch the installer, e.g.:
1. k3OS LiveCD & Installer
2. k3OS Installer only
3. k3OS Rescue Shell
Presumably you would still want to make #1 the default (to prevent breaking any `packer` builds)?
After selecting "K3OS Installer only", it would automatically login as `rancher` and run `sudo k3os install` and present me with the installation wizard.

**Describe alternatives you've considered**
Modifying the live mode and forcing `inittab` to bypass the rancher user login entirely. It seems hacky.

**Additional context**
ISO installers (such as Ubuntu) start with the installer and allow the user to 'drop down' into the OS. I would prefer this but suspect that `packer` builds wouldn't appreciate this step.

CC @dweomer because we were talking about this feature in Rancher Slack #k3os channel

**Comment by philipsparrow** [comment]
I manually edited the "LiveCD & Installer" Grub entry to `k3os.mode=install` and it worked as I wanted.
I've created a branch for this change but I should understand how to test this before making a PR.

https://github.com/philipsparrow/k3os/tree/grub-install-option

**Comment by dweomer** [comment]
@philipsparrow please submit this as a PR as I would like to include your changes in the next release.

**Comment by philipsparrow** [comment]
> @philipsparrow please submit this as a PR as I would like to include your changes in the next release.

Thanks, done: https://github.com/rancher/k3os/pull/507

**Comment by dweomer** [comment]
Fixed via #507
