### ISSUE TITLE
Building k3os iso.

### ISSUE THREAD

**Issue by dieteradant** [rancher/k3os#50]
Any tips on getting me started building the iso image ?

**Comment by curx** [comment]
have you locked at https://github.com/rancher/k3os/tree/master/images?

**Comment by dieteradant** [comment]
My question got answered by @ibuildthecloud in commit:
https://github.com/rancher/k3os/commit/2d66456356c972ff32efd6cd03836cf5fa892617#diff-04c6e90faac2675aa89e2176d2eec7d8
Thanks !
