### ISSUE TITLE
Does Crontab work in k3os?

### ISSUE THREAD

**Issue by gbarton** [rancher/k3os#501]
Been trying to write a few scripts that kick off after the host has booted and periodically do some work, but failing miserably trying to get cron to run.

Can see what I mean by creating a hello world script in /home/rancher/test:
```
#!/bin/bash
echo $(date) >> /tmp/cron.out
```

make file executable
```
chmod +x /home/rancher/test
```

create crontab folder&file:
```
mkdir /var/spool/cron/crontabs
touch /var/spool/cron/crontabs/root
```

Edit crontab and add:
```
 * * * * /home/rancher/test
```

Start crontab:
```
rc-service crond start
```

No output ever shows up in /tmp.  No logs to /var/log, yet service says its running:
```
rc-service crond status
 * status: started
```

**Comment by gbarton** [comment]
Answering my own question that it does, just have to use it a certain way:

Starting
```
rc-service crond start
```

Adding a cron entry:
```bash
# writing to the root crontab file directly, only this file and only for user root works
echo '*/2 * * * * /etc/filename > /root/filename' >> /etc/crontabs/root

# Normal recommended ways through crontab command don't work:
(crontab -l 2>/dev/null; echo "*/5 * * * * /path/to/job -with args") | crontab -
crontab -l -u user | cat - filename | crontab -u user -
```

I put those lines in write_files and run_cmd's so they are written, added to cron and crond is started each time.

**Comment by bemanuel** [comment]
> Answering my own question that it does, just have to use it a certain way:
> 
> Starting
> 
> ```
> rc-service crond start
> ```
> 
> Adding a cron entry:
> 
> ```shell
> # writing to the root crontab file directly, only this file and only for user root works
> echo '*/2 * * * * /etc/filename > /root/filename' >> /etc/crontabs/root
> 
> # Normal recommended ways through crontab command don't work:
> (crontab -l 2>/dev/null; echo "*/5 * * * * /path/to/job -with args") | crontab -
> crontab -l -u user | cat - filename | crontab -u user -
> ```
> 
> I put those lines in write_files and run_cmd's so they are written, added to cron and crond is started each time.
rc-update add crond default
