### ISSUE TITLE
Clarity over which release file to use for Raspberry pi 4

### ISSUE THREAD

**Issue by iandstanley** [rancher/k3os#502]
Just a quickie question here 

There are a ton of files on the releases tab  ....Congrats on getting so many releases out the door 

I'm a little confused however with the number of arm releases and which is best for the Raspberry pi 4

any enlightenment would be appreciated

**Comment by nazarewk** [comment]
It's arm64, but you won't be able to boot it straight away on Raspberry Pi 4 (it doesn't set up RPi's bootloader), you will need to bake it using https://github.com/sgielen/picl-k3os-image-generator

**Comment by iandstanley** [comment]
Thanks

> On 30 May 2020, at 19:40, Krzysztof Nazarewski <notifications@github.com> wrote:
> 
> ﻿
> It's arm64, but you won't be able to boot it straight away on Raspberry Pi 4 (it doesn't set up RPi's bootloader), you will need to bake it using https://github.com/sgielen/picl-k3os-image-generator
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.


-- Email domain proudly hosted at https://migadu.com
