### ISSUE TITLE
VMware deployment

### ISSUE THREAD

**Issue by kmkramer** [rancher/k3os#51]
When using VMware to fire one of these up, which Guest Operating System should I be using on  ESXi 6.5.0.

I spun one up with the v0.1.0 iso and did the auto login, but neither `kubectl` nor `sudo os-config` were found.

using latest iso now.

thanks

**Comment by tfiduccia** [comment]
@kmkramer - i would use v0.2.0- k3os-amd64.iso for VMWare.  If you do the automatic login, make sure you have a config file that has a password.  It will create a server with username=rancher, password whatever you set in config.  Once it reboots enter the credentials and give it a minute then you should be able to say "kubectl get nodes" and see your server.

After auto-login has been completed and installed to disk, os-config is no longer available, that is why you don't see it.
