### ISSUE TITLE
Booting from USB device leads to mounting error

### ISSUE THREAD

**Issue by joda01** [rancher/k3os#527]
**Version (k3OS / kernel)**
v0.11.0-m2
5.4.0-37

**Architecture**
amd64

**Describe the bug**
When trying to install K3OS from USB stick an error: already mounted or moint poit busy error occurs

**To Reproduce**
*  Flash the ISO to USB stick.
*  Boot from USB stick to live system.
*  Start installer with sudo k3os install

**Expected behavior**
*  Installation should start

**Actual behavior**
*  Installation interrupted with error already mounted or moint poit busy error 

**Additional context**
*  No problem when booting from CDROM
*  Also see closed case #358

**Comment by joda01** [comment]
When generating a bootable USB device from the generated iso, 4 partitions are generated. But the device represent itself as just single partition device. For mounting the mount point /dev/sdb must be used not as expected /dev/sdb3. Mounting sdb3 leads to an error ```already mounted or moint poit busy error occurs```.

In the install.sh script the function *get_iso()* is looking for the partition named K3OS. Such a partition is found at /dev/sdb3. Now the install script tries to mount sdb3 but it has to mount sdb instead because of the special structure of the partition table of the USB device.

I suggest a workaround in the install.sh script to remove the number at the end of sdx devices before mounting.

**See the quick and dirty workaround on my fork: https://github.com/joda01/k3os/blob/%231_boot_error_from_usb/install.sh line 218 to 222.**

**Comment by Kampe** [comment]
We're seeing this same issue on bootable USB

**Comment by scalpel4k** [comment]
same here. the patch works like a charm. thx

**Comment by dweomer** [comment]
#528 does not work on my NUC hardware. I get the mount point busy for the /dev/sdb. I will try to adapt it to try the old way first, then try the bare device.
