### ISSUE TITLE
Interrupting k3os-upgrade-kernel script breaks server kernel

### ISSUE THREAD

**Issue by geek-soft** [rancher/k3os#533]
**Version (k3OS / kernel)**
0.10.0 but other versions are likely affected as well

**Architecture**
x86_64

**Describe the bug**
It is possible to break K3OS server by first triggering kernel upgrade and next interrupting download process before it completed. This destructive behaviour is only possible in scenario when server already uses most up-to-date version of the kernel. Other cases seems to be safe because download is carried out to new location which is linked as current only when download finished successfully.

**To Reproduce**
1. Install fresh installation of K3OS 0.10.0 
2. Run `/share/rancher/k3os/scripts/k3os-upgrade-kernel` script
3. Interrupt script after `Upgrading k3os kernel to ${KERNEL_VERSION}` is printed
4. Restart OS

**Expected behavior**
Script should compare available version online with version already installed and do not perform update when kernel is already installed.

**Actual behavior**
Script optimistically redirects kernel that is being downloaded to `${KERNEL_VERSION}/initrd` which is linked as current. In case download is interrupted `${KERNEL_VERSION}/initrd` will contain interrupted content which in turn will cause kernel panic upon restart.

**Additional context**
None

**Comment by zimme** [comment]
The upgrade scripts were deprecated in version 0.9.0 in favour of the upgrade controller. I don't believe Rancher will spend time fixing this, but as I was part of writing the upgrade scripts I would be willing to review any changes to the scripts and maybe @dweomer would consider merging those fixes.

**Comment by dweomer** [comment]
@geek-soft as @zimme says, these scripts have been deprecated (since v0.9.0 or shortly thereafter) and are therefore not supported.
