### ISSUE TITLE
The version of qemu-ga is a little old

### ISSUE THREAD

**Issue by lojurn** [rancher/k3os#536]
The version of qemu-ga is a little old  ,   I want to know if have a plan to update it to 5.X version。

**Comment by dweomer** [comment]
In k3OS the qemu guest agent, along with all other user-space software, comes from Alpine. Right now we are based off of Alpine 3.11. Alpine 3.12 is now available but to make testing and validation easier I have not bumped this yet for k3OS. However we will in the next release.

**Comment by lojurn** [comment]
thank you for response.
