### ISSUE TITLE
Multiple gettys fighting over tty1/console

### ISSUE THREAD

**Issue by brandond** [rancher/k3os#538]
**Version (k3OS / kernel)**
v0.11.0-rc1

**Architecture**
amd64

**Describe the bug**
When attempting to log in to the console, username/password input does not appear to be recognized properly. If you hit return repeatedly without entering username or password, the prompt alternates between /dev/ttys1 and /dev/console every time you hit return.

**To Reproduce**
Install k3os from ISO, wait for host to reboot to login prompt.

**Expected behavior**
Able to log in to system

**Actual behavior**
Cannot log in.

**Additional context**
This worked properly under v0.10.3 so it appears to be a recent issue. If you hit ctrl-alt-f2 and switch to tty2 you can log in fine.

**Comment by brandond** [comment]
![image](https://user-images.githubusercontent.com/370103/87102708-862ee000-c207-11ea-82f2-f8d3ce96f3f4.png)

**Comment by slaterjon** [comment]
Getting something similar myself.  When booted i get two login prompts one for /dev/console and /dev/tty1 .

1. When you login accepts username
2. hit enter gives you password prompt
3. enter password and hit enter
4. the password you entered then is printed on screen and you are give a 2nd password prompt
5. typeing and hitting enter does nothing
6. after 60 seconds you get a time out and prompt for /dev/console comes back up
7. a second or two latter you get a 2nd timeout and the /dev/tty1 login shows up

Screenshots:
login screens at boot:
![login_prompts_tty1_dev-console](https://user-images.githubusercontent.com/2977387/87494673-dbeef800-c60c-11ea-8573-d5d6eb56dc64.png)


Screen when trying to login:
![login_password_password](https://user-images.githubusercontent.com/2977387/87494696-edd09b00-c60c-11ea-8488-22d963efd8be.png)


Going to tty2 (ctrl-alt-f2) allows me to login correctly

**Comment by slaterjon** [comment]
If you login to the box with tty2 (ctrl-alt-f2) and as root edit /boot/grub/grub.cfg

change this line:
  linux (loop0)/vmlinuz printk.devkmsg=on console=tty1 console=console 

to this:

  linux (loop0)/vmlinuz printk.devkmsg=on console=tty1

it will stop loading both and only load tty1 allowing you to login as normal
At least this is what worked for me

**Comment by dweomer** [comment]
I think this issue is related to the changes made by https://github.com/rancher/k3os/pull/504
