### ISSUE TITLE
apk add failed

### ISSUE THREAD

**Issue by kerneltravel** [rancher/k3os#54]
$ apk add vim
ERROR: Unable to lock database: Read-only file system
ERROR: Failed to open apk database: Read-only file system

but by mount get that  /  mount point is "rw" mounted.

**Comment by cvernooy23** [comment]
I think this is due to /usr being mounted as read only and /bin & /sbin being symlinked to /usr/bin & /usr/sbin, respectively

attempting to change the root directory in which to install packages while using apk add {package} produces a similar error, but says "no such file or directory"

**Comment by wenerme** [comment]
Why not setup apk properly ? Alpine support [lbu](https://wiki.alpinelinux.org/wiki/Alpine_local_backup), seems a good fit for this.

**Comment by cvernooy23** [comment]
I can only guess as to the developers intentions. I don't know if they plan to have packages managed by the abstraction layer they may put in or if the idea is to make a system that cannot have "proper" package management. Of course none of this makes it more secure, a piece of malware just has to be compiled prior to saving to a directory that can be written to, or be in the class of "in memory". I would be interested in an official position on all of this as well.

**Comment by gprasath** [comment]
I hit this issue. Is there any workaround to get rid off this?

**Comment by dweomer** [comment]
From the `README.md` (**_emphasis_** mine):
> k3OS is a Linux distribution designed to remove as much as possible OS maintenance in a Kubernetes cluster. **_It is specifically designed to only have what is need to run k3s_**. Additionally the OS is designed to be managed by kubectl once a cluster is bootstrapped. Nodes only need to join a cluster and then all aspects of the OS can be managed from Kubernetes. Both k3OS and k3s upgrades are handled by the k3OS operator.

Software installation via Alpine's `apk` is not supported.
