### ISSUE TITLE
rpc.statd cannot start due to missing /var/lib/nfs/

### ISSUE THREAD

**Issue by stevefan1999-personal** [rancher/k3os#547]
**Version (k3OS / kernel)**
k3OS v0.11.0-rc1

**Architecture**
amd64

**Describe the bug**
ditto in title

**To Reproduce**
run any NFS PV mount but with RWX

**Expected behavior**
Because remote locking is required, rpc.statd will also be started automatically

**Actual behavior**
rpc.statd cannot create NFS state because the folder /var/lib/nfs/ doesn't even exist yet

**Additional context**
need to run `sudo mkdir /var/lib/nfs/`  to each node and it will resume service automatically afterwards

**Comment by dweomer** [comment]
Working on a fix for this, but easily addressable in the meantime via a [`run_cmd`](https://github.com/rancher/k3os#init_cmd-boot_cmd-run_cmd) in `config.yaml` or as a kernel parameter.
