### ISSUE TITLE
[Q] Disable servicelb 

### ISSUE THREAD

**Issue by DarkBlaez** [rancher/k3os#557]
All:

How can servicelb be disabled? I know on install of k3os I can issue

k3s_args
"--no-deploy=traefik"

What can be done to disable servicelb? can I disable it if the cluster is already installed ? or what is the mechanism to do so.

I ask because this is interfering with metalLB. Please advise as to the best way. I would hate to have to reinstall the cluster so how to remove it within an operating cluster? or if on install what is the correct k3s_args or verified manner to do so?

Thanks
DB

**Comment by DarkBlaez** [comment]
Aldo, what is the correct format to disable upon install. Seems the docs are all over the place as all of this is influx.

**Comment by dweomer** [comment]
`--no-deploy` was the original flag to eschew deploying builtin services but has been deprecated for `--disable`, with the same semantics for specifying multiple services. `--disable` works differently in that it will also attempt to delete extant resources associated with the specified builtin.

I run a home lab with k3OS on NUCs and use metallb. There is no need to disable traefik if you want to make use of metallb but you will need to disable servicelb.

**Comment by DarkBlaez** [comment]
Thanks. so --disable servicelb or --disable=servicelb

**Comment by DarkBlaez** [comment]
Is this the correct cloud-init? I ask because I am seeing that it is not creating the node correctly and thus not bringing up the services correctly so that the connection is refused upon performing just a simple kubectl from the console.
k3os:
  k3s_args:
  - “--disable servicelb”


Also, simple checks on the cloud-init upon ingestion prior to processing on an install would provide much cleaner validation

**Comment by dweomer** [comment]
This will not work because it is passing two arguments as a single argument as explained in https://github.com/rancher/k3os/blob/master/README.md#k3osk3s_args
```yaml
k3os:
  k3s_args:
  - "--disable servicelb"
```

instead, it should be either
```yaml
k3os:
  k3s_args:
  - "--disable=servicelb"
```

or

```yaml
k3os:
  k3s_args:
  - "--disable"
  - "servicelb"
```

**Comment by DarkBlaez** [comment]
Thanks. I ended up surmising that and tested and the results are still a more or less inaccessible cluster. with any command sent to kubectl giving an error indicating somehow that it is defaulting to localhost:8080. I am going to trim up the cloud-init and find out what is going on since I have placed the argument as you've indicated

**Comment by DarkBlaez** [comment]
for some reason it did not like the modules: options. I will check in to this further. Thanks. Lets leave this open for a bit until I can completely determine what the exact issue is.

**Comment by DarkBlaez** [comment]
It seems it did not like the modules: directive for some reason so I removed it and everything comes up as I am expecting with servicelb disabled. Thank you very much for your support and assistance
