### ISSUE TITLE
password is incorrect

### ISSUE THREAD

**Issue by bobishere** [rancher/k3os#576]
K3OS v0.11.0
Kernel 5.4.0-37-generic on an x86_64 (/dev/tty1)
**Version (k3OS / kernel)**

**Architecture**

**Describe the bug**

 after installing the OS, when login with user ,I input 'rancher' and password was 'rancher' too,but  the result was 'Login incorrect'.what's the default correct password?
**To Reproduce**

**Expected behavior**

**Actual behavior**

**Additional context**

**Comment by dweomer** [comment]
@bobishere how did you install, via `k3os install` from on the cli from live boot? Many a time I have thought I typed in "rancher" when in fact I've just hit <enter> at the prompt, resulting in an empty string for the password which is always reject except for during live boot. This can also happen when supplying a `config.yaml` if you neglect to put a value in for `k3os.password` the default is an invalid empty string. If you have access to the grub boot menu you can override the password for a single boot by setting the `k3os.password` kernel parameter and then setting the password in a `config.yaml` and rebooting.

**Comment by zhengcan** [comment]
I fixed the same issue by using rescue mode to modify config.yaml.
Updating kernel parameter in grub boot menu is useless for me.

**Comment by arbourd** [comment]
> the default is an invalid empty string

shouldn't we force a required password, in that case?
