### ISSUE TITLE
[Question] Best place on ISO to place air-gap images

### ISSUE THREAD

**Issue by fatwookie** [rancher/k3os#588]
When remastering the CDROM, what would be the best place to put the K3S air-gap images so the images can be copied into `/var/lib/rancher/k3s/agent/images/` during the installation? Usage of air-gap images is described here: https://rancher.com/docs/k3s/latest/en/installation/airgap/#manually-deploy-images-method

I am aware of the `write_files` option in `config.yaml` but putting 100's megabytes of Base64 doesn't seem to be best-practice :-)

**Comment by dweomer** [comment]
We don't have a good general solution for this. Likely dropping images under `/k3os/system/images` or similar combined with altering the `install.sh` script to copy anything in `/k3os/system/images/` to `/var/lib/rancher/k3s/agent/images/` is the most straight forward solution.

**Comment by dweomer** [comment]
@fatwookie Okay, so. I reviewed [`install.sh`](https://github.com/rancher/k3os/blob/v0.11.1/install.sh#L133) (it's been some months) and I think if you put your airgapped image tarballs under `/k3os/data/var/lib/rancher/k3s/agent/images/` on the remastered ISO you would have a general air-gapped solution.

**Comment by fatwookie** [comment]
> 
> 
> @fatwookie Okay, so. I reviewed [`install.sh`](https://github.com/rancher/k3os/blob/v0.11.1/install.sh#L133) (it's been some months) and I think if you put your airgapped image tarballs under `/k3os/data/var/lib/rancher/k3s/agent/images/` on the remastered ISO you would have a general air-gapped solution.

Thanks @dweomer , that seems to do the trick. On a side note, this resulted in a situation where the created partitions weren't large enough to hold all images. Is there any specific reason for specifying the very specific 750MB as the partition size in  [`install.sh`](https://github.com/rancher/k3os/blob/v0.11.1/install.sh#L133)?

**Comment by dweomer** [comment]
@fatwookie I bumped that up from 500 to 750 when k3s was around 1.0. I think it is a vestigial optimization to prevent aggressive writes all over solid state media. If you need to to be bigger you should apply a patch during ISO remaster.

**Comment by fatwookie** [comment]
OK thanks for clarifying that @dweomer!
