### ISSUE TITLE
How to rsyslog?

### ISSUE THREAD

**Issue by hyacin75** [rancher/k3os#604]
Hey all,

I've searched and searched and searched to no avail (over a couple weeks now even).  What is the best way to export the system logs to a remote syslog server?  I've seen a couple different things in the ROS docs that don't apply here.  I tried updating my boot config with netconsole details but nothing arrives at the Logstash node.  On most systems I just add a \*.\* line at the end of /etc/rsyslog.conf, but no such thing exists on k3os, and there's no package manager to install anything :-/

Thanks.

**Comment by zimme** [comment]
You'll need to build your own k3os iso from source that includes `rsyslog` if you need that. Add whatever packages you need in this file and it will be installed in the k3os system installed. https://github.com/rancher/k3os/blob/master/images/00-base/Dockerfile

**Comment by hyacin75** [comment]
Awesome!  That'll do it!  Thank you so much!!
