### ISSUE TITLE
LVM service is not started at boot

### ISSUE THREAD

**Issue by PhoenixMage** [rancher/k3os#610]
**Version (k3OS / kernel)**
k3os version v0.19.2-dev.4

**Architecture**
aarch64/armv7l

**Describe the bug**
Persistent storage such as rook-ceph rely on lvm devices being created at boot time. Not sure if this is the same for longhorn as I havent used it.
In my case /dev/ceph-* is not created and rook-ceph fails to provision existing osds on boot.

**To Reproduce**
Deploy rook-ceph successfully and reboot node.
rook-ceph-osd-# will fail to initialise due to /dev/ceph-* not being created

**Expected behavior**
lvm service running after reboot
/dev/ceph-* created on boot by lvm service

**Actual behavior**
/dev/ceph-* is not created due to lvm service being stopped

**Comment by dweomer** [comment]
@PhoenixMage would a [`run_cmd`](https://github.com/rancher/k3os#init_cmd-boot_cmd-run_cmd) work? e.g.:
```yaml
# /var/lib/rancher/k3os/config.yaml
run_cmd:
- rc-service lvm start
```

We try not to start services that will not necessarily be needed/used and the `boot_cmd`/`run_cmd` facility can fill this kind of gap. If this does not suffice please let me know!

**Comment by PhoenixMage** [comment]
Thanks @dweomer, this will suit my needs.
