### ISSUE TITLE
"--disable traefik" does not work

### ISSUE THREAD

**Issue by EugenMayer** [rancher/k3os#627]
0.11.1

**Version (k3OS / kernel)**
0.11.1

**Architecture**
Linux k3os 5.4.0-48-generic #52 SMP Sat Sep 26 08:27:15 UTC 2020 x86_64 GNU/Linux

**Describe the bug**
When starting the k3s this blocks it:

```
time="2020-12-07T20:26:26Z" level=fatal msg="flag provided but not defined: -disable traefik"
```

When i add `- "--disable traefik" and then run `k3os install` the quotes are removed

**To Reproduce**
Add this to the `cloud-init.yaml`

```yaml
k3os:
   k3s_args:
   - --disable traefik
```

**Expected behavior**
Disable traefik

**Actual behavior**
service fails to start

**Comment by dweomer** [comment]
@EugenMayer as per the docs here, https://github.com/rancher/k3os#k3osk3s_args, please try:

**Comment by EugenMayer** [comment]
Thanks, 

```
k3os:
   k3s_args:
   - --disable=traefik
``` 

worked. Sorry i rather looked at the k3s cli param docs and the k3s docs, where `--disable traefik` was used. Thanks for clarifying
