### ISSUE TITLE
Bump k3s version to v1.19.5+k3s2 And Release

### ISSUE THREAD

**Issue by futuretea** [rancher/k3os#638]
Thanks for helping us to improve k3OS! We welcome all feature requests. Please fill out each area of the template so we can better understand the request. ***You can delete this message portion of the bug report.***

**Is your feature request related to a problem? Please describe.**
The new release v0.2.0 of `rancher/harvester` will support HA. 
This feature depends on the `embedded etcd` of k3s.
Since k3s v1.19.5+k3s1, the embedded etcd of k3s is already stable.

**Describe the solution you'd like**
dump k3s version to latest version `v1.19.5+k3s2` and release

**Describe alternatives you've considered**

**Additional context**

**Comment by kwadroke** [comment]
Looks like it's already been bumped to v1.19.5+k3s2, just not released yet.
https://github.com/rancher/k3os/commit/7cb1c62fc9da14e7af25511af82f4611141fc73b

I'm eagerly awaiting this release so that I could test & deploy an HA environment based off of K3os.

**Comment by dweomer** [comment]
Addressed via #636
