### ISSUE TITLE
KVM not available

### ISSUE THREAD

**Issue by kwiesmueller** [rancher/k3os#649]
**Version (k3OS / kernel)**
k3os version v0.11.1

**Architecture**
x86_64

**Describe the bug**
I tried to install kubevirt on k3os, but can't manage to enable kvm.
Even when setting the kvm module, the `/dev/kvm` device does not become available and I can't find a way to debug the problem as I can't install any kvm related tooling.
I know harvester is using k3os but so far I failed to extract the details on how harvester manages to pull it off.

**To Reproduce**
1. Install k3os
2. Install https://kubevirt.io/quickstart_cloud/
3. Create a VM
4. See the VM being stuck in `scheduled` because of missing kvm and vnet support.

**Expected behavior**
A way to enable KVM and install Kubevirt

**Actual behavior**
KVM does not become available

**Additional context**
Running on a bare metal machine.

**Comment by CuBiC3D** [comment]
Loading the required kernel modules should fix this:
```
k3os:
  modules:
  - kvm
  - vhost_net
  ```

**Comment by kwiesmueller** [comment]
I already tried that, still can't use it.

**Comment by CuBiC3D** [comment]
I just verified on 0.11.1 and kubevirt did run the VM.

**Comment by kwiesmueller** [comment]
Okay, then I'll try this again this evening. Thanks for that!

**Comment by kwiesmueller** [comment]
```sh
$ sudo k3os config --dump
k3os:
  modules:
  - kvm
  - vhost_net
  token: ********
ssh_authorized_keys:
- github:kwiesmueller
$ ls -la /dev/kvm
ls: cannot access '/dev/kvm': No such file or directory
```
Not sure what's wrong. Contacting provider now, maybe it's not supported.
`/dev/vhost-net` seems to be there, so the setting itself works I guess.

**Comment by CuBiC3D** [comment]
I'm running on bare-metal, since you said provider, nesting might be (and probably is) not supported.

**Comment by kwiesmueller** [comment]
Lack of virtualization support was the problem :man_facepalming:
