### ISSUE TITLE
What ARM boards would the community like supported?

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/k3os#65]
I'd like to use this issue so people can comment on what ARM boards should be supported by k3OS.  It would work best if one comment per board was create and then other can just :+1: the comment so we can get a count.

As a bonus if you are already running k3s on some existing Linux distro on these boards if you could please share what those distros are that would be great.  We don't have resources to maintain kernels for tons of boards to if we can use kernels and boot loaders from other community images and just replace the user space with k3OS then we should be able to support a good number of boards.

**Comment by alexellis** [comment]
Raspberry Pi 3 - raspbian lite

**Comment by alexellis** [comment]
Raspberry Pi 2 - raspbian lite

**Comment by alexellis** [comment]
Asus Tinkerboard

**Comment by pagong** [comment]
Odroid C2

**Comment by pagong** [comment]
Odroid XU4, HC1, HC2

**Comment by pagong** [comment]
Odroid N2

**Comment by rektide** [comment]
The [hikey970](https://www.96boards.org/product/hikey970/) 96board.

**Comment by VRspace4** [comment]
Libre Computer ROC-RK3328-CC
Armbian Bionic

**Comment by VRspace4** [comment]
Nvidia Jetson TK1
Ubuntu 16.04

**Comment by VRspace4** [comment]
Nvidia Jetson Xavier
Ubuntu 18.04

**Comment by mwpaa** [comment]
Raspberry Pi Zero (Worker-only, if it fits)

**Comment by mwthink** [comment]
Raspberry Pi Zero for **density**

**Comment by alexellis** [comment]
Raspberry Pi Zero is hard to support due to the armv6 images not being published by the Kubernetes project and the amount of RAM / CPU required. I struggle to get the RPi2 working even with K3s (it's armv7)

**Comment by wallies** [comment]
Marvel Macchiatobin

**Comment by mejlholm** [comment]
NVIDIA Jetson Nano 
Ubuntu disco dingo 19.04

**Comment by tobru** [comment]
**Orange Pi Win Plus**

I'm running it with [Armbian](https://www.armbian.com/orange-pi-win/) and k3s is also already running fine on an 8-node Orange Pi Win Plus cluster. See also [Kubernetes on OrangePI ARM64](https://tobru.ch/kubernetes-on-orangepi-arm64/) (This cluster will be displayed on KubeCon Barcelona 2019).

**Comment by Fufuhu** [comment]
Rock64

**Comment by christian-korneck** [comment]
Raspberry Pi 3B+

**Comment by runningman84** [comment]
AML-S905X-CC (Le Potato)

**Comment by beriberikix** [comment]
Beaglebone Black & BBB Wireless

**Comment by WebedMJ** [comment]
Raspberry Pi2/3 and Tinkerboard please.

**Comment by alexellis** [comment]
Better to vote with :+1: than repeat the suggestions with new comments

**Comment by kisskillkiss** [comment]
Armbian Bionic : Sopine A64&Sopine Cluster(Include 7 Sopine A64), thx, Please!

**Comment by mejlholm** [comment]
Orange pi pc2 with Armbian

**Comment by stellirin** [comment]
My cluster uses Orange Pi Zero on Fedora

It uses the generic mainline kernel compiled by Fedora with a device specific uBoot on the SPI chip, so actually I'm asking for a generic ARMv7 image that will work for many devices with the right uBoot.

**Comment by arnarg** [comment]
A generic "bring-your-own-u-boot" aarch64 image.

**Comment by ptone** [comment]
NXP iMX8 series
https://www.nxp.com/products/processors-and-microcontrollers/arm-based-processors-and-mcus/i.mx-applications-processors/i.mx-8-processors:IMX8-SERIES

**Comment by loqutus** [comment]
i'm running k3s on 1 raspberry pi 3 b+ with raspbian, and 5 orange pi pc's with armbian xenial.

**Comment by zimme** [comment]
Odroid-C1+

**Comment by Plaquevent** [comment]
Raspberry Pi 3 B+

**Comment by itavero** [comment]
Raspberry Pi 4!

**Comment by sajanki** [comment]
Orange Pi Win Plus

**Comment by jbhannah** [comment]
Raspberry Pi 3B, running k3s on openSUSE Leap 15.1 ARM64.

**Comment by riker09** [comment]
NanoPi M4

**Comment by PhoenixMage** [comment]
RockPi 4

**Comment by tpjg** [comment]
Nvidia TX2

**Comment by plod** [comment]
Rockpro64

**Comment by ppouliot** [comment]
Sopine/pine64

**Comment by ulm0** [comment]
NanoPi r2s
