### ISSUE TITLE
K3OS node starting will be failed when DHCP server has bind a Hostname in lan router

### ISSUE THREAD

**Issue by toby1991** [rancher/k3os#655]
**Version (k3OS / kernel)**
* k3os-amd64-v0.11.1
* k3os-amd64-v0.19.5-rc.1

**Architecture**
route: ASUS AC88u
KVM

**Describe the bug**
When DHCP server has bind a Hostname in lan router, k3os cannot starting the node.
`/var/log/k3-service.log` will log many error like `node my_k3s not found`, `containerd.sock no such file or directory`, the `my_k3s` is the kvm machine's Hostname which ip binded with in DHCP server.

**To Reproduce**
Use the `iso` install to disk, then `tail -f /var/log/k3-service.log`, or `kubectl get node`

**Expected behavior**
Run successfully

**Actual behavior**
Cannot run node properly

**Additional context**
When I remove the `Hostname` in DHCP server, and redeploy a new KVM, the node works.

![image](https://user-images.githubusercontent.com/5897356/106450483-3758d880-64c0-11eb-8ef8-8213a10c475f.png)

**Comment by toby1991** [comment]
Issue related:  https://github.com/rancher/k3os/issues/47

Seems that containerd or k3s will use the machine's ip to **query dhcp server**, then use the resolved **hostname as node name** or something else ?

**Comment by dweomer** [comment]
Leaving the hostname blank on the DHCP would fix it I assume (which is what it looks like was tried with success) but you should also be able to override via https://github.com/rancher/k3os#hostname
