### ISSUE TITLE
[Q] Cloud-init worked under v0.11.0 but not in v0.11.1

### ISSUE THREAD

**Issue by DarkBlaez** [rancher/k3os#668]
All

back in 2020 when I built a small 4 node cluster I used this cloud-init on the main node. Seemed to work. Now I am rebuilding and using v0.11.1 and I am getting an ERROR cannot convert Yaml to Json at a specific line 15. I have not been able to figure this out since everything has remained the same and looks good. Thoughts?
```
ssh_authorized_keys:
- ssh-rsa
X
X
X
X
X
X
X
X
hostname: k3s000

k3os:
  k3s_args:
  - "--disable=servicelb,traefik”
  dns_nameservers:
  - 8.8.8.8
  - 1.1.1.1
  ntp_servers:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
  password: XXXXX
  token: XXXXX
```

Thanks in advance
DB

**Comment by dharmendrakariya** [comment]
@DarkBlaez dayyym!!, literally around 10-15 times I tried and my cloud init is not being used, and finally I landed on issues and just saw yours. I am working with 3 node HA cluster and facing the same issue.

**Comment by DarkBlaez** [comment]
Yes the cloud-init parsing in k3os install is a basic shit-show. Does not even take in to consideration when the format changes and the docs are outdated

-DB

**Comment by DarkBlaez** [comment]
I cannot find anything wrong with your cloud-init. Trust me the biggest pain in the ass is the parsing in the install. Why no one actually does fresh installs against a set of cloud-init templates is beyond me.

**Comment by DarkBlaez** [comment]
For my issue its from the - "--" part of the disable option. Try running your config through http://www.yamllint.com

Mine blows with a
 (<unknown>): found unexpected end of stream while scanning a quoted scalar at line 17 column 7 which in my new config is the --disable

**Comment by DarkBlaez** [comment]
Try this parser as it will convert to JSON so you can see what. is taking place
https://yaml-online-parser.appspot.com

**Comment by DarkBlaez** [comment]
While I was able to get past the Yaml issue, seems the installer ignores the --disbable directive now. Seems like with every release someone boogers up things. Clearly isolated testing on fresh device or VMs is not taking place, otherwise this level of injected issues per release would not keep popping up. Probably the same reason why the security scans in Rancher seem to never get resolved to remove the attack vectors

**Comment by dharmendrakariya** [comment]
@DarkBlaez Thanks for the respose:) , However I don't find any issue with my above cloud init, and also yamllint says its perfect, json also looks good to me. anyway will try something else see.
