### ISSUE TITLE
How to disable default system upgrade controller and plan

### ISSUE THREAD

**Issue by Dev-Time** [rancher/k3os#683]
I want to use my own plan and system upgrade controller manifest, but it keeps being overwritten by the default manifest in `/usr/share/rancher/k3s/server/manifests`.  I have custom taints on my nodes, so the default system upgrade controller deployment wont work for me.  Every time I deploy my customized system upgrade controller, the default one replaces it.  The same goes for the plan.  I tried deleting the files in `/usr/share/rancher/k3s/server/manifests`, however that filesystem is read only, so the delete fails.

Is there a way to disable the deployment of the default system upgrade controller and plan?

**Comment by brlbil** [comment]
You can remove the default plan and controller at run time like below. So they would not be created at all.

```
run_cmd:
- rm -f /var/lib/rancher/k3s/server/manifests/system-upgrade-controller.yaml
- rm -f /var/lib/rancher/k3s/server/manifests/system-upgrade-plans/k3os-latest.yaml
```

**Comment by Dev-Time** [comment]
worked great, thanks
