### ISSUE TITLE
Latest build k3s constantly crashes with cloudconfig....

### ISSUE THREAD

**Issue by rsliotta** [rancher/k3os#687]
**Version (k3OS / kernel)**
rome [/etc/init.d]# cat /etc/os-release
NAME="k3OS"
VERSION="k3OS v0.20.4-k3s1r0"
ID=k3os
ID_LIKE=alpine
PRETTY_NAME="k3OS v0.20.4-k3s1r0"
VERSION_ID="v0.20.4-k3s1r0"
HOME_URL="https://k3os.io/"
SUPPORT_URL="https://k3os.io/"
BUG_REPORT_URL="https://github.com/rancher/k3os/issues"
ISO_URL="https://github.com/rancher/k3os/releases/download/v0.20.4-k3s1r0/k3os-amd64.iso"

5.4.0-70-generic #78 SMP Fri Mar 26 17:09:23 UTC 2021

**Architecture**
x86_64

Guys installed with a cloud-config file.  It DOES look like everything is configured properly...  This is the k3s-service file that was generated.  supervised-daemon is mis-placing the '--' for argument separation after the k3s. See below.  k3s keeps crashing.  I manually run the supervise-daemon moving the '--' prior to the k3s and it works as expected.  I am guessing k3s was ignoring the '--' in a prior release?

```
#!/sbin/openrc-run

depend() {
    after network-online
    want cgroups
}

start_pre() {
    rm -f /tmp/k3s.*
}

supervisor=supervise-daemon
name=k3s-service
command="/sbin/k3s"
command_args="server \
	'--node-label' \
	'k3os.io/mode=local' \
	'--node-label' \
	'k3os.io/version=v0.20.4-k3s1r0' \
	'--node-label' \
	'region=us-west-1' \
	'--node-label' \
	'somekey=somevalue' \
        '--cluster-cidr=10.44.0.0/16' \
        '--service-cidr=10.45.0.0/16' \
        '--cluster-dns=10.44.0.10' \
        '--no-deploy=traefik' \
	'--disable-agent' "

output_log=/var/log/k3s-service.log
error_log=/var/log/k3s-service.log

pidfile="/var/run/k3s-service.pid"
respawn_delay=5
respawn_max=0

set -o allexport
if [ -f /etc/environment ]; then source /etc/environment; fi
if [ -f /etc/rancher/k3s/k3s-service.env ]; then source /etc/rancher/k3s/k3s-service.env; fi
set +o allexport
```

ps-ef output

``root     30014     1  0 19:01 ?        00:00:00 supervise-daemon k3s-service --start --stdout /var/log/k3s-service.log --stderr /var/log/k3s-service.log --pidfile /var/run/k3s-service.pid --respawn-delay 5 --respawn-max 0 /sbin/k3s -- server --node-label k3os.io/mode=local --node-label k3os.io/version=v0.20.4-k3s1r0 --node-label region=us-west-1 --node-label somekey=somevalue --cluster-cidr=10.44.0.0/16 --service-cidr=10.45.0.0/16 --cluster-dns=10.44.0.10 --no-deploy=traefik --disable-agent
``
also in /var/log/messages 

May  2 19:32:51 rome daemon.info supervise-daemon[6240]: Child command line: /sbin/k3s server --cluster-cidr 10.44.0.0/16 --service-cidr 10.45.1.0/16 --node-label k3os.io/mode=local --node-label k3os.io/version=v0.20.4-k3s1r0
May  2 19:32:51 rome daemon.warn supervise-daemon[6055]: /sbin/k3s, pid 6240, exited with return code 1

and 

2021-05-02T19:33:52.892227376Z" level=info msg="Starting k3s v1.20.4+k3s1 (838a906a)"
time="2021-05-02T19:33:52.893309785Z" level=fatal msg="starting kubernetes: preparing server: failed to get CA certs: Get \"https://127.0.0.1:6443/cacerts\": dial tcp
**To Reproduce**
See above

**Expected behavior**
k3s should start.  Currently it crashes non-stop

I have tested about 20 various combinations to see if I can get that to move but with no success.

Also of note....

If I install the same ISO without cloudconfig it generates and almost identical k3-service file and it DOES START.  It's possible some other dependency is missing in the cloudconfig.

**Comment by rsliotta** [comment]
An update from continued testing....

If I simply run the failing service MANUALLY as root, it WORKS!

supervise-daemon k3s-service --start --stdout /var/log/k3s-service.log --stderr /var/log/k3s-service.log --pidfile /var/run/k3s-service.pid --respawn-delay 5 --respawn-max 0 /sbin/k3s -- server --cluster-cidr 10.44.0.0/16 --service-cidr 10.45.1.0/16 --node-label k3os.io/mode=local --node-label k3os.io/version=v0.20.4-k3s1r0

But if I do service k3s-service start/stop it does not......

Now I am thoroughly  confused!

**Comment by cjellick** [comment]
I see that your manual run does not match the k3s arguments from the one in your original comment. Does the manual run work with the exact same args? I specifically wondering if the `--disable-agent` is making a difference.

**Comment by rsliotta** [comment]
I have tried with and without in both cases.  Same result.

I suspect it os more like something lower level from the cloudconfig like included kernel modules

But that does not explain why if I run it on the command line from the cloud config it works.

**Comment by rsliotta** [comment]
All.  I figured it out.  Operator error.  I had the server_url from the example and did not read the definition.  I commented it out and it is working.  I thought it was the master but it is for the agent!
