### ISSUE TITLE
--no-deploy traefik servicelb not respected

### ISSUE THREAD

**Issue by bbergshaven** [rancher/k3os#69]
I'm having trouble disabling the auto deployment of traefik. 
I have added:
```
k3os-8393 [/var/lib/rancher/k3os]$ cat config.yaml
k3os:
  k3s_args:
  - server
  - "--no-deploy traefik servicelb"
```
and deleted all the jobs/pods/services related to traefik, but still after 120minutes everything is recreated.

ps-ax gives the following:
```
 2007 ?        S      0:00 supervise-daemon k3s-service --start --pidfile /var/run/k3s-service.pid --respawn-delay 5 /sbin/k3s -- server --no-deploy traefik
 2009 ?        Ssl   96:56 /sbin/k3s server --no-deploy traefik
```

Any thoughts on what I can do to stop this from happing? I have to deploy my own LB and Ingress server to handle TLS, ACME etc..

**Comment by tfiduccia** [comment]
@bbergshaven - You can accomplish this by turning it off on k3os installation
1.  Create a config.yaml that has
```
k3os:
  k3_args:
  - server
  - "--no-deploy traefik"
```
2.  On installation of k3os, either add it to the automated Installation (k3os.install.config_url = config.yaml)  or you can add it manually through the setup steps.  Once i did that, you will notice that traefik was not installed.
![image](https://user-images.githubusercontent.com/11514927/57411190-b319da00-71a1-11e9-86d6-67fd48874560.png)

**Comment by majkrzak** [comment]
No matter what is set in the `config.yaml` is affecting traefik deployment. Also removing `/var/lib/rancher/k3s/server/manifests/traefik.yaml` does not help. Only way to keep is uninstalled is to remove everything except `job.batch/helm-install-traefik` otherwise it will be recreated.

Really, please fix it and document...

**Comment by majkrzak** [comment]
@bbergshaven `kubectl -n kube-system delete helmcharts traefik` have to be also invoked to get rid of default traefik...

**Comment by davidhiendl** [comment]
I'm also experiencing this issue. If I only disable **traefik** it works but once you disable **traefik** and **servicelb** both are started.

**Working:**
```
--no-deploy traefik
```

**Not working variants**
```
--no-deploy traefik,servicelb
--no-deploy traefik servicelb
--no-deploy traefik --no-deploy servicelb
```

**Comment by davidnuzik** [comment]
A few days ago we added the ability to specify --no-deploy with comma delimited entries (2 or more entries). The next k3os release should include an updated k3s release with this ability. See https://github.com/rancher/k3s/pull/851

**Comment by dweomer** [comment]
On master (v0.8.0+) this is working for both
```
k3os:
  k3s_args:
  - "--no-deploy"
  - "traefik,servicelb"
```
and
```
k3os:
  k3s_args:
  - "--no-deploy=traefik,servicelb"
```

**Comment by ElanHasson** [comment]
neither of those work for me.

```
k3os:
        password: supersecure
        k3s_args:
                - server
                - "--no-deploy=traefik,servicelb"
```

is what worked for me. v0.10

**Comment by guiguan** [comment]
use `--disable=traefik` instead. `--no-deploy` is deprecated

**Comment by ElanHasson** [comment]
Where is this stuff even documented? I feel like there is only the code and the readme in the repo root.

Am I missing something?

**Comment by guiguan** [comment]
> Where is this stuff even documented? I feel like there is only the code and the readme in the repo root.
> 
> 
> 
> Am I missing something?

Yes, their docs are very confusing. I got the info from `k3s server -h`. Then I found they did have this: https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/#kubernetes-components

**Comment by ElanHasson** [comment]
Thanks! I've seen the k3s docs, but it's difficult to discern the separation between `k3os` and `k3s`.

Very blended together, and unclear what is part of what.

consider:

```
k3os:
  k3s_args:
```

so `k3s_args` is a child of `k3os`? Why not it's own section, or a different file that is passed to k3s config? vs os?

Is my model of this broken :(

**Comment by kruton** [comment]
Note that `--no-deploy` and `--disable` are slightly different. `--disable` will delete any file with that name, so make sure your custom traefik file is not named `traefik.yaml` or you will be confused as to why it doesn't exist.
