### ISSUE TITLE
Trying to disable Klipper LB but k3s server crash with message "flag provided but not defined: -disable servicelb"

### ISSUE THREAD

**Issue by ogandoe** [rancher/k3os#723]
**Version (k3OS / kernel)**
k3os version v0.21.1-k3s1r0
5.4.0-73-generic #82 SMP Thu Jun 3 02:29:43 UTC 2021

**Architecture**
x86_64

**Describe the bug**
I'm trying to disable Klipper LB passing this argunment to config.yaml   "--disable servicelb"

**To Reproduce**
This is my config.yaml

#Master
hostname: k3os-master
k3os:
  k3s_args:
    - server
    - "--disable servicelb"
**Expected behavior**
Klipper LB should be disable

**Actual behavior**
k3s server crashing with this error in k3s-service.log

time="2021-06-23T20:03:12Z" level=fatal msg="flag provided but not defined: -disable servicelb"

**Comment by dweomer** [comment]
@ogandoe from the README at https://github.com/rancher/k3os#k3osk3s_args:

**Comment by ogandoe** [comment]
My config.yaml was wrong.
to disable this service the correct configuration should be set in this way 
#Master
hostname: k3os-master
k3os:
k3s_args:
- server
- "--disable"
- "servicelb"

**Comment by ogandoe** [comment]
> @ogandoe from the README at https://github.com/rancher/k3os#k3osk3s_args
> ### `k3os.k3s_args`
> 
> Arguments to be passed to the k3s process. The arguments should start with `server` or `agent` to be valid.
> `k3s_args` is an exec-style (aka uninterpreted) argument array which means that when specifying a flag with a value one
> must either join the flag to the value with an `=` in the same array entry or specify the flag in an entry by itself
> immediately followed the value in another entry, e.g.:
> 
> ```yaml
> # K3s flags with values joined with `=` in single entry
> k3os:
>   k3s_args:
>   - server
>   - "--cluster-cidr=10.107.0.0/23"
>   - "--service-cidr=10.107.1.0/23"
> 
> # Effectively invokes k3s as:
> # exec "k3s" "server" "--cluster-cidr=10.107.0.0/23" "--service-cidr=10.107.1.0/23" 
> ```
> 
> ```yaml
> # K3s flags with values in following entry
> k3os:
>   k3s_args:
>   - server
>   - "--cluster-cidr"
>   - "10.107.0.0/23"
>   - "--service-cidr"
>   - "10.107.1.0/23"
> 
> # Effectively invokes k3s as:
> # exec "k3s" "server" "--cluster-cidr" "10.107.0.0/23" "--service-cidr" "10.107.1.0/23" 
> ```

Thanks @dweomer  my mistake!!

Regards

Emiliano
