### ISSUE TITLE
dhcp get killed by connman?

### ISSUE THREAD

**Issue by liyimeng** [rancher/k3os#724]
**Version (k3OS / kernel)**

0.21.0-k3s1r0

5.4.72
**Architecture**

x86_64
**Describe the bug**

I have ethernet connection on eth0, and have conman/main.conf written at config.yaml file like this 

```
write_files:
- content: |-
    [General]
    AllowHostnameUpdates=false
    PreferredTechnologies=ethernet,wifi
    NetworkInterfaceBlacklist=vmnet,vboxnet,virbr,ifb,docker,veth,cni,flannel,tap,eth1,eth2,eth3,vn
  encoding: ""
  owner: root
  path: /etc/connman/main.conf
  permissions: "0644"

when connman service start, it remove IP address on eth0 and set it some 169.254.x.x

```
**To Reproduce**

- boot k3os,  no IPv4 address.  
- run 'sudo udhcpc eth0' to achieve correct IPv4 address 
- sudo 'sudo service connman restart'  IP address is removed, and a 169.254.x.x address is appeared after a while.
- 
**Expected behavior**

**Actual behavior**

**Additional context**

Should get a proper IP address like the one retrieve via udhcpc

kvm vm

**Comment by liyimeng** [comment]
it turns out to be my virtual machine problem.

**Comment by skirsten** [comment]
@liyimeng 

I have the exact same problem. But I don't see how it could be a problem with my virtual machine.
Could you please elaborate what the problem was or how to fix it?

Note: I do not have a custom config file like this example. Version `v0.20.7-k3s1r0`
