### ISSUE TITLE
Docker installation: Unsupported distribution 'k3os'

### ISSUE THREAD

**Issue by insbire** [rancher/k3os#725]
**Version (k3OS / kernel)**
harvester: 0.2.0
k3OS: v0.20.7-k3s1r0

**Architecture**
x86_64

**Describe the bug**
Cant install docker to k3os, unsupported distribution 'k3os'

**Expected behavior**
Docker installation successful.

**Actual behavior**
<img width="296" alt="2021-07-06-143934" src="https://user-images.githubusercontent.com/86938244/124556502-ee3ff280-de6a-11eb-8f18-9d0055f0522a.png">

**Comment by liangyuanpeng** [comment]
Maybe should create issue to [rancher/install-docker](https://github.com/rancher/install-docker)

**Comment by vincent99** [comment]
The install script is basically just docker's with the versions pinned instead of always installing the latest.  They are not going to support k3os, and we are not going to support docker on k3os (which includes k3s/containerd).

**Comment by pratikbalar** [comment]
@liangyuanpeng issue is disabled at [rancher/install-docker](https://github.com/rancher/install-docker)

**Comment by pratikbalar** [comment]
@insbire I also need docker in k3os man
