### ISSUE TITLE
Is k3os dead?

### ISSUE THREAD

**Issue by bkupidura** [rancher/k3os#742]
So looks like k3os is lagging behind k3s.

Question is k3os is still activly developed?

Last release is 3 months old (4 Jun), and there are almost no commits since then.

Can you please share any roadmap for k3os?

**Comment by dweomer** [comment]
k3OS is not dead per se but it is true that it hasn't had much attention lately. When I have the time I try to bump the kernel and/or k3s but I have gotten behind. We do not have a road-map and have not prioritized any new work for this project. Contributions welcome!
