### ISSUE TITLE
Building ISO with baked in custom config.yaml

### ISSUE THREAD

**Issue by AdamSutch** [rancher/k3os#75]
Can we get instructions on where to place a customized config.yaml to have it baked into an iso/image when building.

Ideally if this doesn't exist it would be awesome to have a .gitignored location where I can drop my config, run `make` and get an iso that I can use for a completely unattended install.

**Comment by jcardoso-bv** [comment]
In my brief testing, you simply place your custom config in `/k3os/system/config.yaml` when baking your ISO.

**Comment by davidnuzik** [comment]
Closing. If need any additional help please re-open the issue and ask.
