### ISSUE TITLE
k3os.install.silent=true still asks final Configuration question

### ISSUE THREAD

**Issue by tfiduccia** [rancher/k3os#76]
Version - v0.2.0

Steps:
1.  Setup VMWare machine
2.  During boot process, press e to get into GNU Grub
3.  In linux add k3os.mode=install & k3os.install.silent=true
4.  Ctrl-x to save and continue

Results:  Silent work all the way through the installation.  The final Configuration question is asked and requires input
![image](https://user-images.githubusercontent.com/11514927/57405643-d2aa0600-7193-11e9-8449-e17a7416c849.png)

**Comment by jcardoso-bv** [comment]
Bug confirmed in `v0.2.0` but appears to have been resolved in `v0.2.1-rc2`.

**Comment by acrom18** [comment]
Also can confirm this behavior for `v0.2.0`.

**Comment by acrom18** [comment]
Can confirm, this is resolved in `v0.2.1`.

**Comment by dweomer** [comment]
Fixed via #85
