### ISSUE TITLE
ISO image doesn't boot on Proxmox UEFI VM

### ISSUE THREAD

**Issue by jdeluyck** [rancher/k3os#792]
**Version (k3OS / kernel)**
ISO build v0.20.11-k3s2r1

**Architecture**
amd64 proxmox 7.0-13

**Describe the bug**
ISO image fails to boot when configuring a proxmox vm using UEFI.

**To Reproduce**
Setup proxmox vm with q35, and bios OVMF. Boot image, gives error that it cannot start:

![screenshot](https://user-images.githubusercontent.com/5451787/137730226-ebd2263d-1f6a-41b0-b3b2-790a7a0f867d.png)

Booting eg. a Debian ISO works fine with the same VM configuration.
Booting the ISO with standard BIOS (non-UEFI) works.

**Expected behavior**
ISO should boot in UEFI mode

**Actual behavior**
Hangs on Access Denied

**Comment by Dotmaster5** [comment]
> @jdeluyck is secure boot enabled?

You made my Day, i try to start serval times an Image of HomeAsisstant with UEFI Bios. It was the Secure boot option that denies the accses to the virtual Drive... disabled the Secure Boot and everithing works like a charm ;-)

**Comment by Xaekai** [comment]
Thanks, this helped me. I ran into the same issue.
Whoever decided a virtualized UEFI bios should _default_ to secure boot on should be kicked in butt.

**Comment by sfxworks** [comment]
I did the same and still can't seem to boot https://store.steampowered.com/steamos/buildyourown as it requires uefi
