### ISSUE TITLE
K3OS VMs querying their own DNS like crazy

### ISSUE THREAD

**Issue by immanuelfodor** [rancher/k3os#84]
Hi Everyone, 

I created two k3os one-node cluster VMs in Proxmox lately, and when I checked the PiHole DNS blackhole service on the LAN, which is for filtering out ads and other unwanted sites, I saw that the k3os VMs are querying themselves in an extreme measure, like 30+ thousand times in a day. After I created the first VM, it ran for some two days, then I destroyed it for experimentation purposes, then created the current one yesterday, which does the same. 

Both VM's init was the following: 

```bash
# get latest iso once (it was 0.2.0-rc6 previously this week)
cd /var/lib/vz/template/iso
GITHUB_REPO="rancher/k3os"
GITHUB_LATEST_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/${GITHUB_REPO}/releases/latest)
GITHUB_LATEST_VERSION=$(echo $GITHUB_LATEST_RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
GITHUB_ORIG_FILE="k3os-amd64.iso"
GITHUB_DOWN_FILE="k3os-amd64-${GITHUB_LATEST_VERSION//v/}.iso"
GITHUB_URL="https://github.com/${GITHUB_REPO}/releases/download/${GITHUB_LATEST_VERSION}/${GITHUB_ORIG_FILE}"
wget -O $GITHUB_DOWN_FILE $GITHUB_URL

qm create 200 --agent 1 --cores 2 --ide2 local:iso/${GITHUB_DOWN_FILE},media=cdrom --memory 3072 --name k-node-1 --net0 virtio,bridge=vmbr0,firewall=1 --numa 0 --onboot 1 --ostype l26 --scsi0 local-lvm:8 --scsihw virtio-scsi-pci --sockets 1
qm start 200

# login in VNC as rancher
sudo passwd rancher
# type rancher
# exit VNC

# ssh login using a DHCP allocated address
ssh rancher@10.0.0.88
# type rancher

sudo os-config
# Install to disk: 1
# Cloud-init: N
# Github SSH: N
# Type new pass 2 times
# Wifi: N
# Server: 1
# Cluster secret: generate new with `openssl rand -hex 20` in a new tab
# Continue: y
# reboot

# host info changes, so remove it
ssh-keygen -f "/root/.ssh/known_hosts" -R 10.0.0.88
ssh rancher@10.0.0.88
# using new pass
```

Nothing else was set up, I just looked around inside the VMs. The process could be easier on the setup side (no VNC interaction, automated network settings, installed image by default), but there are other issues open for cloud-init, etc. so I won't bother with it.

My only problem now is the VM going berserk on querying its own DNS, it amounts to ~90% of the local DNS traffic these days. Can it be stopped somehow? I would like to use fixed IPs, but I just haven't got the time to set it up yet with conman (I also need to look into conman's config options, new stuff to me). Could it stop the flood?

**Comment by immanuelfodor** [comment]
I tried to assign a fix IP to the one-node K3OS cluster VM to stop the DNS query flood but it doesn't help, the VM still bombards the DNS server.

```bash
ETH0=$(sudo connmanctl services | awk '{ print $3 }' | while read -r s1; do sudo connmanctl services $s1 | grep -q "eth0" && echo "$s1"; done)
echo $ETH0 
# ethernet_abcdef01234_cable
sudo connmanctl config $ETH0 --ipv4 manual 10.0.0.33 255.255.255.0 10.0.0.1 --nameservers 10.0.0.2
sudo connmanctl config $ETH0 --domains my.local
sudo connmanctl config $ETH0 --ipv6 off
sudo service connman restart
```

Last 24 hours, 31000+ queries:

![image](https://user-images.githubusercontent.com/21174107/57569070-1f8a1880-73f0-11e9-8895-874203939d54.png)

**Comment by immanuelfodor** [comment]
The interval seems to be 10s according to the log, if it helps.

**Comment by immanuelfodor** [comment]
I created a `run_cmd` file to set up networking through `cloud-init` as can be seen in my other comment here https://github.com/rancher/k3os/issues/68#issuecomment-492089070 and this DNS query issue still exists.

**Comment by davidnuzik** [comment]
This should be fixed with a recent change; this should work much better now. Could you try with the latest RC? https://github.com/rancher/k3os/releases/tag/v0.3.0-rc2

**Comment by immanuelfodor** [comment]
Thanks, sure, though I'll need a couple of days to test it, will report back when ready.

**Comment by immanuelfodor** [comment]
I was too curious, so allocated time in the morning to test it with `v0.3.0`, it seems the DNS querying is reduced to 1 per hour at every `XX:00:00`, wonderful, thanks for the fix!
