### ISSUE TITLE
fail to get ssh key from Github

### ISSUE THREAD

**Issue by xlight** [rancher/k3os#88]
dns at [::1] not work
![image](https://user-images.githubusercontent.com/77911/57573014-be486080-7454-11e9-8138-ed332d5aa8a2.png)

**Comment by tedder** [comment]
I'm seeing the same thing. The boot screen says both eth0 and wlan0 are 'DOWN'. That is probably because they are at eno1 and .. something else for wlan that I've forgotten.

I don't know how to fix. I'm trying this on an Intel NUC with very vanilla hardware, booting from the ISO on USB without any config (other than specifying the drive, 'server', and my ssh key). So I can't even access the machine after install since the rancher password gets wiped.

**Comment by tedder** [comment]
progress:
- set a `password`, so at least I can log in and diagnose now.
- networking is at `eth0`, not `eno1` for k3os. It has an IP from my DHCP server, and I can ssh in remotely (with the password).
- The pre-login banner still says eth0 DOWN.
- There's no ssh key (no files in `~/.ssh/`)

I don't know how much confidence I should have in k3os given this. If I tail k3s-service.log it is full of "`watch chan error: EOF`" as mentioned in rancher/k3s/issues/463.

**Comment by danopz** [comment]
Same for me, installed K3OS from bootable USB to HDD.
When booting into K3OS I'm getting:

> ERRO[0000] failed to authorize SSH key github:danopz: Get https://github.com/[…]: dial tcp: lookup github.com on [::1]:53: read udp [::1]:53466->[::1]:53: read: connection refused

**Comment by vincent99** [comment]
https://github.com/rancher/k3os/pull/136

**Comment by brandon099** [comment]
Same problem here trying to run from HDD on an Intel NUC. #136 did not seem to fix it. I've tried with the latest release which includes that change, with the same result. The machine has an IP from my DHCP server as well, so network is up but banner shows down (update-issue script) and the SSH pubkey pulling appears to be happening before network is ready still.

**Comment by oalhassane** [comment]
I'm having the same issue on v0.11.0 running on a physical device. 
![2020-09-15_09-58](https://user-images.githubusercontent.com/39570316/93222369-e0cf4580-f73c-11ea-8166-d77dba19e5fe.png)

**Comment by Alxandr** [comment]
Same here. Just set up a new machine, same issue.

**Comment by brittonhayes** [comment]
I am also still experiencing this issue. K3OS deployed on an Intel NUC and working fine other than the github-based ssh key feature has the exact same failure mentioned above.

Is there any way we could re-open this issue, as I don't believe this has been fully resolved?
