### ISSUE TITLE
sysctl erring during boot, when set through config.yaml

### ISSUE THREAD

**Issue by tfiduccia** [rancher/k3os#95]
Version - v0.2.1-rc1

1.  Create a config.yaml with
```
k3os:
  sysctl:
    kernel.panic: 60
  password: asdf

```
2.  During boot process, press e to get into GNU Grub
3.  On linux cmdline add k3os.mode=install k3os.install.config_url="config yaml url"
4.  Try to log in.  

results:  Won't let you cause the sysctl field is erring on boot.  "ERRO[0000] json: cannot unmarshal nuber into Go struct field K3OS.sysctls of type string"
![image](https://user-images.githubusercontent.com/11514927/57661105-543bd280-759e-11e9-8143-a4470735285d.png)

**Comment by gabrielegiammatteo** [comment]
putting double quotes around `kernel.kptr_restrict` value solved this issue for me. 
```
  sysctls:
    kernel.printk: 4 4 1 7
    kernel.kptr_restrict: "1"
```
